
fbref_data <- fbref_data %>%
  count(home) %>%
  rename(fbref_name = home) %>%
  filter(n > 8)

fuzzy_join <- fbref_data %>%
  distinct(fbref_name) %>%
  fuzzyjoin::stringdist_left_join(hist_buch_data %>% distinct(home), by = c('fbref_name' = 'home'), max_dist = 1) %>%
  arrange(fbref_name) %>%
  rename(buch_name = home) %>%
  mutate(pin_name = fbref_name)

fuzzy_join

datapasta::dp_set_max_rows(305)
datapasta::dpasta(fuzzy_join)

hist_buch_data %>%
  distinct(home) %>%
  arrange(home) %>%
  View()

team_lookup<-
 tibble::tribble(
               ~fbref_name,               ~buch_name,                ~pin_name,
            "ado den haag",               'den haag',           "ado den haag",
                 "ajaccio",                "ajaccio",                "ajaccio",
                    "ajax",                   "ajax",                   "ajax",
                  "alaves",                 "alaves",                 "alaves",
             "almere city",                 "almere",            "almere city",
                 "almeria",                "almeria",                "almeria",
                 "america",           "club america",                "america",
              "america mg",             "america mg",             "america mg",
                  "amiens",                 "amiens",                 "amiens",
                  "angers",                 "angers",                 "angers",
                 "arminia",              "bielefeld",                "arminia",
                  "arouca",                 "arouca",                 "arouca",
                 "arsenal",                "arsenal",                "arsenal",
             "aston villa",            "aston villa",            "aston villa",
                "atalanta",               "atalanta",               "atalanta",
           "athletic club",             "ath bilbao",          "athletic club",
          "atl goianiense",            "atletico go",         "atl goianiense",
          "atl paranaense",            "athleticopr",         "atl paranaense",
             "atlanta utd",            "atlanta utd",            "atlanta utd",
                   "atlas",                  "atlas",                  "atlas",
                "atletico",             "ath bilbao",               "atletico",
         "atletico madrid",             "ath madrid",        "atletico madrid",
        "atletico mineiro",             "atleticomg",       "atletico mineiro",
                "augsburg",               "augsburg",               "augsburg",
                  "austin",              "austin fc",                 "austin",
                 "auxerre",                "auxerre",                "auxerre",
                    "avai",                   "avai",                   "avai",
                    "aves",                   "aves",                   "aves",
              "az alkmaar",             "az alkmaar",             "az alkmaar",
                   "bahia",                  "bahia",                  "bahia",
               "barcelona",              "barcelona",              "barcelona",
                "barnsley",               "barnsley",               "barnsley",
           "bayern munich",          "bayern munich",          "bayern munich",
               "benevento",              "benevento",              "benevento",
                 "benfica",                "benfica",                "benfica",
                   "betis",                  "betis",                  "betis",
         "birmingham city",             "birmingham",        "birmingham city",
               "blackburn",              "blackburn",              "blackburn",
               "blackpool",              "blackpool",              "blackpool",
                "boavista",               "boavista",               "boavista",
                  "bochum",                 "bochum",                 "bochum",
                 "bologna",                "bologna",                "bologna",
                  "bolton",                 "bolton",                 "bolton",
                "bordeaux",               "bordeaux",               "bordeaux",
             "botafogo rj",            "botafogo rj",            "botafogo rj",
             "bournemouth",            "bournemouth",            "bournemouth",
                   "braga",               "sp braga",                  "braga",
              "bragantino",             "bragantino",             "bragantino",
               "brentford",              "brentford",              "brentford",
                 "brescia",                "brescia",                "brescia",
                   "brest",                  "brest",                  "brest",
                "brighton",               "brighton",               "brighton",
            "bristol city",           "bristol city",           "bristol city",
                    "bsad",                   "bsad",                   "bsad",
                 "burnley",                "burnley",                "burnley",
                   "cadiz",                  "cadiz",                  "cadiz",
                    "caen",                   "caen",                   "caen",
                "cagliari",               "cagliari",               "cagliari",
                 "cambuur",                "cambuur",                "cambuur",
            "cardiff city",                "cardiff",           "cardiff city",
                "casa pia",               "casa pia",               "casa pia",
                   "ceara",                  "ceara",                  "ceara",
              "celta vigo",                  "celta",             "celta vigo",
             "cf montreal",            "cf montreal",            "cf montreal",
             "chapecoense",          "chapecoensesc",            "chapecoense",
               "charlotte",              "charlotte",              "charlotte",
            "charlton ath",               "charlton",           "charlton ath",
                  "chaves",                 "chaves",                 "chaves",
                 "chelsea",                "chelsea",                "chelsea",
            "chicago fire",           "chicago fire",           "chicago fire",
                  "chievo",                 "chievo",                 "chievo",
           "clermont foot",               "clermont",          "clermont foot",
         "colorado rapids",        "colorado rapids",        "colorado rapids",
           "columbus crew",          "columbus crew",          "columbus crew",
             "corinthians",            "corinthians",            "corinthians",
                "coritiba",               "coritiba",               "coritiba",
           "coventry city",               "coventry",          "coventry city",
               "cremonese",              "cremonese",              "cremonese",
                 "crotone",                "crotone",                "crotone",
               "cruz azul",              "cruz azul",              "cruz azul",
                "cruzeiro",               "cruzeiro",               "cruzeiro",
          "crystal palace",         "crystal palace",         "crystal palace",
                     "csa",                    "csa",                    "csa",
                  "cuiaba",                 "cuiaba",                 "cuiaba",
               "dc united",              "dc united",              "dc united",
           "de graafschap",          "de graafschap",          "de graafschap",
               "den bosch",              "den bosch",              "den bosch",
            "derby county",                  "derby",           "derby county",
                   "dijon",                  "dijon",                  "dijon",
                "dortmund",               "dortmund",               "dortmund",
              "dusseldorf",     "fortuna dusseldorf",             "dusseldorf",
                  "dynamo",                 "dynamo",                 "dynamo",
               "dynamo fc",         "houston dynamo",              "dynamo fc",
                   "eibar",                  "eibar",                  "eibar",
          "eint frankfurt",          "ein frankfurt",         "eint frankfurt",
                   "elche",                  "elche",                  "elche",
                   "emmen",               "fc emmen",                  "emmen",
                  "empoli",                 "empoli",                 "empoli",
                "espanyol",                "espanol",               "espanyol",
                 "estoril",                "estoril",                "estoril",
                 "estrela",                "estrela",                "estrela",
                 "everton",                "everton",                "everton",
               "excelsior",              "excelsior",              "excelsior",
               "famalicao",              "famalicao",              "famalicao",
                 "farense",                "farense",                "farense",
           "fc cincinnati",          "fc cincinnati",          "fc cincinnati",
               "fc dallas",              "fc dallas",              "fc dallas",
            "fc eindhoven",          "psv eindhoven",           "fc eindhoven",
               "fc juarez",                 "juarez",              "fc juarez",
                "feirense",               "feirense",               "feirense",
               "feyenoord",              "feyenoord",              "feyenoord",
              "fiorentina",             "fiorentina",             "fiorentina",
                "flamengo",            "flamengo rj",               "flamengo",
              "fluminense",             "fluminense",             "fluminense",
               "fortaleza",              "fortaleza",              "fortaleza",
         "fortuna sittard",            "for sittard",        "fortuna sittard",
                "freiburg",               "freiburg",               "freiburg",
               "frosinone",              "frosinone",              "frosinone",
                  "fulham",                 "fulham",                 "fulham",
                   "genoa",                  "genoa",                  "genoa",
                  "getafe",                 "getafe",                 "getafe",
          "gil vicente fc",            "gil vicente",         "gil vicente fc",
                  "girona",                 "girona",                 "girona",
            "go ahead eag",        "go ahead eagles",           "go ahead eag",
                   "goias",                  "goias",                  "goias",
                 "granada",                "granada",                "granada",
                  "gremio",                 "gremio",                 "gremio",
          "greuther furth",         "greuther furth",         "greuther furth",
               "groningen",              "groningen",              "groningen",
             "guadalajara",     "guadalajara chivas",            "guadalajara",
                "guingamp",               "guingamp",               "guingamp",
            "hamburger sv",                "hamburg",           "hamburger sv",
             "hannover 96",               "hannover",            "hannover 96",
              "heerenveen",             "heerenveen",             "heerenveen",
              "heidenheim",             "heidenheim",             "heidenheim",
           "hellas verona",                 "verona",          "hellas verona",
         "heracles almelo",               "heracles",        "heracles almelo",
              "hertha bsc",                 "hertha",             "hertha bsc",
              "hoffenheim",             "hoffenheim",             "hoffenheim",
           "holstein kiel",          "holstein kiel",          "holstein kiel",
            "huddersfield",           "huddersfield",           "huddersfield",
                  "huesca",                 "huesca",                 "huesca",
               "hull city",                   "hull",              "hull city",
                   "inter",                  "inter",                  "inter",
             "inter miami",            "inter miami",            "inter miami",
           "internacional",          "internacional",          "internacional",
            "ipswich town",                "ipswich",           "ipswich town",
               "juventude",              "juventude",              "juventude",
                "juventus",               "juventus",               "juventus",
                    "koln",                "fc koln",                   "koln",
               "la coruna",              "la coruna",              "la coruna",
               "la galaxy",     "los angeles galaxy",              "la galaxy",
              "las palmas",             "las palmas",             "las palmas",
                   "lazio",                  "lazio",                  "lazio",
                   "lecce",                  "lecce",                  "lecce",
            "leeds united",                  "leeds",           "leeds united",
                 "leganes",                "leganes",                "leganes",
          "leicester city",              "leicester",         "leicester city",
                    "lens",                   "lens",                   "lens",
                    "leon",                   "lyon",                   "leon",
                 "levante",                "levante",                "levante",
              "leverkusen",             "leverkusen",             "leverkusen",
                   "lille",                  "lille",                  "lille",
               "liverpool",              "liverpool",              "liverpool",
              "lobos buap",             "lobos buap",             "lobos buap",
                 "lorient",                "lorient",                "lorient",
          "los angeles fc",         "los angeles fc",         "los angeles fc",
              "luton town",                  "Luton",             "luton town",
                    "lyon",                   "lyon",                   "lyon",
                "mainz 05",                  "mainz",               "mainz 05",
                  "malaga",                 "malaga",                 "malaga",
                "mallorca",               "mallorca",               "mallorca",
         "manchester city",               "man city",        "manchester city",
          "manchester utd",             "man united",         "manchester utd",
                "maritimo",               "maritimo",               "maritimo",
               "marseille",              "marseille",              "marseille",
                "mazatlan",            "mazatlan fc",               "mazatlan",
                    "metz",                   "metz",                   "metz",
               "mgladbach",              "mgladbach",              "mgladbach",
           "middlesbrough",          "middlesbrough",          "middlesbrough",
                   "milan",                  "milan",                  "milan",
                "millwall",               "millwall",               "millwall",
           "minnesota utd",       "minnesota united",          "minnesota utd",
                  "monaco",                 "monaco",                 "monaco",
               "monterrey",              "monterrey",              "monterrey",
             "montpellier",            "montpellier",            "montpellier",
         "montreal impact",            "cf montreal",        "montreal impact",
                   "monza",                  "monza",                  "monza",
              "moreirense",             "moreirense",             "moreirense",
                 "morelia",                "morelia",                "morelia",
          "mvv maastricht",             "maastricht",         "mvv maastricht",
               "nac breda",              "nac breda",              "nac breda",
                "nacional",               "nacional",               "nacional",
                  "nantes",                 "nantes",                 "nantes",
                  "napoli",                 "napoli",                 "napoli",
               "nashville",           "nashville sc",              "nashville",
            "nec nijmegen",               "nijmegen",           "nec nijmegen",
                  "necaxa",                 "necaxa",                 "necaxa",
             "new england", "new england revolution",            "new england",
           "newcastle utd",              "newcastle",          "newcastle utd",
                    "nice",                   "nice",                   "nice",
                   "nimes",                  "nimes",                  "nimes",
            "norwich city",                "norwich",           "norwich city",
          "nottham forest",           "nottm forest",         "nottham forest",
                "nurnberg",               "nurnberg",               "nurnberg",
            "ny red bulls",     "new york red bulls",           "ny red bulls",
                   "nycfc",          "new york city",                  "nycfc",
            "orlando city",           "orlando city",           "orlando city",
                 "osasuna",                "osasuna",                "osasuna",
                 "pachuca",                "pachuca",                "pachuca",
                   "pacos",         "pacos ferreira",                  "pacos",
            "paderborn 07",              "paderborn",           "paderborn 07",
               "palmeiras",              "palmeiras",              "palmeiras",
                "paris sg",               "paris sg",               "paris sg",
                   "parma",                  "parma",                  "parma",
            "pborough utd",              "peterboro",           "pborough utd",
            "philadelphia",     "philadelphia union",           "philadelphia",
            "portimonense",           "portimonense",           "portimonense",
        "portland timbers",       "portland timbers",       "portland timbers",
                   "porto",                  "porto",                  "porto",
                 "preston",                "preston",                "preston",
           "psv eindhoven",          "psv eindhoven",          "psv eindhoven",
                  "puebla",                 "puebla",                 "puebla",
                     "qpr",                    "qpr",                    "qpr",
               "queretaro",              "queretaro",              "queretaro",
          "rayo vallecano",              "vallecano",         "rayo vallecano",
              "rb leipzig",             "rb leipzig",             "rb leipzig",
                 "reading",                "reading",                "reading",
             "real madrid",            "real madrid",            "real madrid",
          "real salt lake",         "real salt lake",         "real salt lake",
           "real sociedad",               "sociedad",          "real sociedad",
                   "reims",                  "reims",                  "reims",
                  "rennes",                 "rennes",                 "rennes",
                 "rio ave",                "rio ave",                "rio ave",
            "rkc waalwijk",               "waalwijk",           "rkc waalwijk",
                    "roma",                   "roma",                   "roma",
                    "roma",                   "roda",                   "roma",
           "rotherham utd",              "rotherham",          "rotherham utd",
            "saintetienne",             "st etienne",           "saintetienne",
             "salernitana",            "salernitana",            "salernitana",
               "sampdoria",              "sampdoria",              "sampdoria",
                "san jose",   "san jose earthquakes",               "san jose",
             "santa clara",            "santa clara",            "santa clara",
                  "santos",                 "santos",                 "santos",
               "sao paulo",              "sao paulo",              "sao paulo",
                "sassuolo",               "sassuolo",               "sassuolo",
              "schalke 04",             "schalke 04",             "schalke 04",
                 "seattle",       "seattle sounders",                "seattle",
                 "sevilla",                "sevilla",                "sevilla",
           "sheffield utd",       "sheffield united",          "sheffield utd",
          "sheffield weds",         "sheffield weds",         "sheffield weds",
             "southampton",            "southampton",            "southampton",
                    "spal",                   "spal",                   "spal",
             "sparta rdam",       "sparta rotterdam",            "sparta rdam",
                  "spezia",                 "spezia",                 "spezia",
            "sport recife",           "sport recife",           "sport recife",
             "sporting cp",              "sp lisbon",            "sporting cp",
             "sporting kc",   "sporting kansas city",            "sporting kc",
                "st louis",          "st louis city",               "st louis",
              "stoke city",                  "stoke",             "stoke city",
              "strasbourg",             "strasbourg",             "strasbourg",
               "stuttgart",              "stuttgart",              "stuttgart",
              "sunderland",             "sunderland",             "sunderland",
            "swansea city",                "swansea",           "swansea city",
                 "tijuana",           "club tijuana",                "tijuana",
                  "toluca",                 "toluca",                 "toluca",
                 "tondela",                "tondela",                "tondela",
                  "torino",                 "torino",                 "torino",
              "toronto fc",             "toronto fc",             "toronto fc",
               "tottenham",              "tottenham",              "tottenham",
                "toulouse",               "toulouse",               "toulouse",
                  "troyes",                 "troyes",                 "troyes",
                  "twente",                 "twente",                 "twente",
                    "uanl",            "uanl tigres",                   "uanl",
                 "udinese",                "udinese",                "udinese",
                    "unam",             "unam pumas",                   "unam",
            "union berlin",           "union berlin",           "union berlin",
                 "utrecht",                "utrecht",                "utrecht",
                "valencia",               "valencia",               "valencia",
              "valladolid",             "valladolid",             "valladolid",
               "vancouver",    "vancouver whitecaps",              "vancouver",
           "vasco da gama",                  "vasco",          "vasco da gama",
                 "venezia",                "venezia",                "venezia",
                "veracruz",               "veracruz",               "veracruz",
              "villarreal",             "villarreal",             "villarreal",
                 "vitesse",                "vitesse",                "vitesse",
                 "vitoria",                "setubal",                "vitoria",
         "vitoria setubal",                "setubal",        "vitoria setubal",
                  "vizela",                 "vizela",                 "vizela",
                "volendam",               "volendam",               "volendam",
                "vvvvenlo",              "vvv venlo",               "vvvvenlo",
                 "watford",                "watford",                "watford",
           "werder bremen",          "werder bremen",          "werder bremen",
               "west brom",              "west brom",              "west brom",
                "west ham",               "west ham",               "west ham",
          "wigan athletic",                  "wigan",         "wigan athletic",
               "willem ii",              "willem ii",              "willem ii",
               "wolfsburg",              "wolfsburg",              "wolfsburg",
                  "wolves",                 "wolves",                 "wolves",
                 "wycombe",                "wycombe",                "wycombe",
                  "zwolle",                 "zwolle",                 "zwolle"
  )

pin_names <- tibble::tribble(
  ~buch, ~pin,
  'St. Louis CITY SC', 'St. Louis City SC',
  'FC Arouca', 'Arouca',
  'Instituto', 'Instituto AC Cordoba',
  'Tulsa Roughnecks', 'FC Tulsa',
  'CA Independiente', 'Independiente',
  'Pau', 'Pau FC',
  'Dijon FCO', 'Dijon',
  "Atletico Goianiense", "AC Goianiense GO",
  "SC Farense", "Sporting Farense",
  "Moreirense", "Moreirense FC",
  "Wurzburger Kickers", "FC Wurzburger Kickers",
  "Western United", "Western United FC",
  "Western Sydney FC", "Western Sydney Wanderers",
  "Colon Santa Fe", "Colon de Santa Fe",
  "Estudiantes", "Estudiantes de La Plata",
  "Newell's Old Boys", "Newells Old Boys",
  "Arsenal Sarandi", "Arsenal de Sarandi",
  "Atletico Tucuman", "Atletico Tucuman",
  "Aldosivi", "CA Aldosivi",
  "Patronato", "Patronato Parana",
  "Central Cordoba Santiago del Estero", "Central Cordoba",
  "Talleres de Cordoba", "CA Talleres de Cordoba",
  "Granada", "Granada CF",
  "VfL Osnabruck", "VfL 1899 Osnabruck",
  "SV Wehen Wiesbaden", "Wehen Wiesbaden",
  "Wigan", "Wigan Athletic",
  "Birmingham", "Birmingham City",
  "Newcastle", "Newcastle United",
  "Stade Rennes", "Rennes",
  "Toulouse", "Toulouse FC",
  "Montpellier", "Montpellier HSC",
  "Angers", "Angers SCO",
  "Paris Saint-Germain", "Paris Saint Germain",
  "TSG Hoffenheim", "Hoffenheim",
  "SC Freiburg", "Freiburg",
  "Fortuna Dusseldorf", "Fortuna Dusseldorf",
  "1. FC Nurnberg", "1 FC Nuremberg",
  "Mainz", "Mainz 05",
  "VfL Wolfsburg", "Wolfsburg",
  "VfB Stuttgart", "Stuttgart",
  "FC Augsburg", "Augsburg",
  "1. FC Magdeburg", "FC Magdeburg",
  "1. FC Union Berlin", "Union Berlin",
  "FC Cologne", "FC Koln",
  "MSV Duisburg", "Duisburg",
  "Hamburg SV", "Hamburger SV",
  "Verona", "Hellas Verona FC",
  'Las Vegas Lights FC', 'Las Vegas Lights',
  "Chievo Hellas Verona FC", "AC Chievo Verona",
  "Internazionale", "FC Internazionale",
  "Atalanta", "Atalanta BC",
  "F.B.C Unione Venezia", "Venezia",
  "Queretaro", "Queretaro FC",
  "CF America", "Club America",
  "Monterrey", "CF Monterrey",
  "Pumas Unam", "Pumas UNAM",
  "Lobos de la BUAP", "CF Lobos de la BUAP",
  "Puebla", "Puebla FC",
  "Leon", "Club Leon",
  "Guadalajara", "Chivas Guadalajara",
  "Tijuana", "Club Tijuana",
  "C.D. Nacional", "CD Nacional Madeira",
  "Desportivo Aves", "Aves",
  "Girona FC", "Girona",
  "Alaves", "Alaves",
  "Levante", "Levante UD",
  "Sevilla FC", "Sevilla",
  "Real Valladolid", "Real Valladolid CF",
  "Villarreal", "Villarreal CF",
  "Athletic Bilbao", "Athletic Club Bilbao",
  "SD Huesca", "Huesca",
  "Orlando City SC", "Orlando City",
  "New York City FC", "New York City",
  "DC United", "D.C. United",
  "Seattle Sounders FC", "Seattle Sounders",
  "Minnesota United FC", "Minnesota United",
  "FC Dallas", "Dallas",
  "Blackburn", "Blackburn Rovers",
  "Wolverhampton", "Wolves",
  "US Pescara", "Delfino Pescara 1936",
  "Pachuca", "CF Pachuca",
  "Club America", "CF America",
  "Atlanta United FC", "Atlanta United",
  "Botafogo", "Botafogo FR RJ",
  "Grêmio", "Gremio FB Porto Alegrense RS",
  "Ceara", "Ceara SC CE",
  "Chapecoense AF", "Chapecoense SC",
  "Avai", "Avai FC SC",
  "CSA", "Centro Sportivo Alagoano",
  "Chongqing Lifan", "Chongqing SWM",
  "Guizhou Renhe", "Beijing Renhe",
  "Hebei China Fortune FC", "Hebei CFFC",
  "Tianjin Quanujian", "Tianjin Tianhai",
  "Guangzhou RF", "Guangzhou R&F",
  "Guangzhou Evergrande", "Guangzhou Evergrande Taobao",
  "Shanghai SIPG", "Shanghai Sipg",
  "Tianjin Teda", "Tianjin Teda FC",
  "Shanghai Greenland", "Shanghai Shenhua",
  "FC Juarez", "FC Juarez",
  "Atletico San Luis", "Atletico San Luis",
  "Morelia", "CA Monarcas Morelia",
  "Santos SP Laguna", "Club Santos Laguna",
  "Toluca", "Deportivo Toluca FC",
  "Newcastle United Jets", "Newcastle Jets",
  "Inter Miami CF", "Inter Miami",
  "Mazatlan FC", "Mazatlan FC",
  "Elche", "Elche CF",
  "Monza", "AC Monza",
  "FC Twente", "FC Twente Enschede",
  "Vitesse", "Vitesse Arnhem",
  "Heracles", "Heracles Almelo",
  "Sparta", "Sparta Rotterdam",
  "PSV", "PSV Eindhoven",
  "AZ", "Az Alkmaar",
  "Az Alkmaar", "AZ Alkmaar",
  "RKC", "RKC Waalwijk",
  "SV Zulte Waregem", "SV Zulte-Waregem",
  "Valenciennes", "Valenciennes FC",
  "Chambly Thelle FC", "FC Chambly Oise",
  "Sporting Gijon", "Gijon",
  "AD Alcorcon", "Alcorcon",
  "Lausanne Sports", "Lausanne",
  "FC Salzburg", "Red Bull Salzburg",
  "Antwerp", "Royal Antwerp",
  "Ludogorets", "Ludogorets 1947",
  "Lugo", "CD Lugo",
  "SD Ponferradina", "Ponferradina",
  "CD Sabadell", "CE Sabadell FC",
  "Logrones", "UD Logrones",
  "SK Sturm Graz", "Sturm Graz",
  "KV Oostende", "Oostende",
  "Niort", "Chamois Niortais FC",
  "US Quevilly", "Quevilly",
  "Dunkerque", "USL Dunkerque",
  "WSG Swarovski Wattens", "WSG Wattens",
  "FC Trenkwalder Admira", "FC Admira Wacker Modling",
  "Sporting de Charleroi", "Charleroi",
  "KAA Gent", "Gent",
  "Mouscron-Peruwelz", "Mouscron Peruwelz",
  "OH Leuven", "Oud-Heverlee Leuven",
  "St. Truidense", "Sint Truiden",
  "Bolton", "Bolton Wanderers",
  "Real Oviedo", "Real Oviedo CF",
  "FC Khimki", "Khimki",
  "SK Brann", "Brann",
  "Rosenborg", "Rosenborg BK",
  "Aalesund", "Aalesunds",
  "Vicenza", "LR Vicenza Virtus",
  "Scunthorpe", "Scunthorpe United",
  "Reggiana", "AC Reggiana",
  "Cremonese", "US Cremonese",
  "Salernitana", "Sportiva Salernitana",
  "Doncaster Rovers", "Doncaster",
  "Milton Keynes Dons", "MK Dons",
  "Shrewsbury Town", "Shrewsbury",
  'Brentford', 'Brentford FC',
  'Norwich City', 'Norwich City FC',
  'Antalyaspor', 'Antalyaspor AS',
  'Goztepe', 'Goztepe SK',
  'Ankaragucu', 'MKE Ankaragucu',
  'Jahn Regensburg', 'SSV Jahn Regensburg',
  'Emmen', 'FC Emmen',
  'Feyenoord', 'Feyenoord Rotterdam',
  'Tondela', 'CD Tondela',
  'Belgrano Cordoba', 'Belgrano',
  'Belenenses', 'Belenenses SAD',
  'Heerenveen', 'SC Heerenveen',
  'Portimonense', 'Portimonense SC',
  'Guimaraes', 'Vitoria Guimarares',
  'Ajax', 'Ajax Amsterdam',
  'Oklahoma City Energy FC', 'OKC Energy FC',
  'Rio Grande Valley FC Toros', 'Rio Grande Valley FC',
  'Birmingham City Legion FC', 'Birmingham Legion FC',
  'Troyes', 'Troyes AC',
  'Loudoun United FC', 'Loudoun United Fc',
  'Santos FC SP Laguna', 'Club Santos Laguna',
  'Birmingham Legion FC', 'Birmingham Legion Fc',
  'Oakland Roots', 'Oakland Roots Sc',
  'El Paso Locomotive FC', 'El Paso Locomotive Fc',
  'Norwich City FC', 'Norwich City',
  'Brentford FC', 'Brentford',
  'Norwich City FC', 'Norwich City',
  'Watford FC', 'Watford',
  'Sportiva Salernitana', 'Salernitana',
  'VfL Bochum', 'Bochum',
  'AFC Bournemouth', 'Bournemouth',
  'NEC', 'NEC Nijmegen',
  'AS Nancy Lorraine', 'AS Nancy-Lorraine',
  'Auxerre', 'AJ Auxerre',
  'Krylia Sovetov', 'Kryliya Sovetov',
  'FK Nizhny Novgorod', 'Olimpiyets Nizhny Novgorod',
  'Rotherham United', 'Rotherham',
  'Wycombe Wanderers', 'Wycombe',
  'Clermont Foot', 'Clermont',
  'Altay', 'Altay Izmir',
  'Burgos', 'CD Burgos',
  'Red Bull SC Bragantino SP', 'Red Bull Bragantino SP',
  'LA Galaxy II', 'Los Angeles Galaxy II',
  'Preston North End', 'Preston',
  'West Bromwich Albion', 'West Brom',
  'Coventry City', 'Coventry',
  'Estoril Praia', 'Estoril',
  'FC St. Pau FCli', 'FC St. Pauli',
  'Crotone', 'FC Crotone',
  'Alessandria', 'US Alessandria Calcio 1912',
  'Sao Pau FClo', 'Sao Paulo FC SP',
  'Sao Paulo FC SP', 'Sao Paulo',
  'FC Sheriff Tiraspol', 'Sheriff Tiraspol',
  'Ludogorets 1947', 'Ludogorets 1945',
  'Feyenoord Rotterdam', 'Feyenoord',
  'FC St. Pauli', 'St Pauli',
  'FC Ingolstadt 04', 'Ingolstadt',
  'SV Sandhausen', 'Sandhausen',
  '1. FC Heidenheim 1846', 'FC Heidenheim',
  'SC Paderborn', 'Paderborn',
  'Cambuur Leeuwarden', 'Cambuur Leeuwaarden',
  'Patronato Parana', 'CA Patronato Parana',
  "Sarmiento", "Sarmiento de Junin",
  'SC Heerenveen', 'Heerenveen',
  'FC Groningen', 'Groningen',
  'Ajax Amsterdam', 'Ajax',
  'PEC Zwolle', 'FC Zwolle',
  '1 FC Nuremberg', 'Nurnberg',
  'SSV Jahn Regensburg', 'Jahn Regensburg',
  'Memphis 901 FC', 'Memphis 901 Fc',
  'SpVgg Greuther Furth', 'Greuther Furth',
  'Montreal Impact', 'CF Montreal',
  'Necaxa', 'Club Necaxa',
  'Tigre', 'CA Tigre',
  'AJ Auxerre', 'Auxerre',
  'US Cremonese', 'Cremonese',
  '1. FC Kaiserslautern', 'Kaiserslautern',
  'FC Emmen', 'Emmen',
  'FC Volendam', 'Volendam',
  'Laval', 'Stade Lavallois',
  'CA Tigres UANL', 'Tigres UANL',
  'Villarreal CF B', 'Villarreal B',
  'SV Darmstadt 98', 'Darmstadt'
)


# ---- uudelleen jarjestys ----

sekasin <- tibble::tribble(
  ~fbref_name,               ~buch_name,                ~pin_name,
  "ado den haag",               "den haag",               "Den Haag",
  "ajaccio",                "ajaccio",                "AC Ajaccio",
  "ajax",                   "ajax",                   "Ajax",
  "alaves",                 "alaves",                 "Alaves",
  "annecy",                 "annecy",                 "Annecy",
  "alcorcon",               "alcorcon",               "Alcorcon",
  "almere city",            "almere city",            "Almere City",
  "almeria",                "almeria",                "Almeria",
  "america",           "club america",             "CF America",
  "america mg",             "america mg",        "America Mineiro",
  "amiens",                 "amiens",                 "Amiens",
  "sd amorebieta",             "amorebieta",             "Amorebieta",
  "albacete",               "albacete",               "Albacete",
  "angers",                 "angers",                 "Angers SCO",
  "fc andorra",                "andorra",             "FC Andorra",
  "arminia",              "bielefeld",              "Bielefeld",
  "arouca",                 "arouca",                 "Arouca",
  "arsenal",                "arsenal",                "Arsenal",
  "arsenal sarandi",        "arsenal sarandi",     "Arsenal de Sarandi",
  "aston villa",            "aston villa",            "Aston Villa",
  "atalanta",               "atalanta",            "Atalanta BC",
  "athletic club",             "ath bilbao",   "Athletic Club Bilbao",
  "atletico",           "atl san luis",      "Atletico San Luis",
  "atl goianiense",            "atletico go",            "Atletico Go",
  "ath paranaense",            "athleticopr",   "Athletico Paranaense",
  "tucuman",            "atl tucuman",       "Atletico Tucuman",
  "atlanta utd",            "atlanta utd",         "Atlanta United",
  "atlas",                  "atlas",                  "Atlas",
  "atletico madrid",             "ath madrid",        "Atletico Madrid",
  "atletico mineiro",             "atleticomg",       "Atletico Mineiro",
  "augsburg",               "augsburg",               "Augsburg",
  "austin",              "austin fc",              "Austin FC",
  "auxerre",                "auxerre",                "Auxerre",
  "argentinos jun",         "argentinos jrs",     "Argentinos Juniors",
  "avai",                   "avai",                   "Avai",
  "aves",                   "aves",                   "Aves",
  "az alkmaar",             "az alkmaar",             "AZ Alkmaar",
  "bahia",                  "bahia",                  "Bahia",
  "barcelona",              "barcelona",              "Barcelona",
  "barnsley",               "barnsley",               "Barnsley",
  "barracas central",       "barracas central",       "Barracas Central",
  "banfield",               "banfield",               "Banfield",
  "bayern munich",          "bayern munich",          "Bayern Munich",
  "benevento",              "benevento",              "Benevento",
  "beerschot",           "beerschot va",              "Beerschot",
  "benfica",                "benfica",                "Benfica",
  "betis",                  "betis",             "Real Betis",
  "birmingham city",             "birmingham",        "Birmingham City",
  "blackburn",              "blackburn",       "Blackburn Rovers",
  "blackpool",              "blackpool",              "Blackpool",
  "boavista",               "boavista",               "Boavista",
  "bochum",                 "bochum",                 "Bochum",
  "burgos",                 "burgos",              "CD Burgos",
  "boca juniors",           "boca juniors",           "Boca Juniors",
  "bologna",                "bologna",                "Bologna",
  "bastia",                 "bastia",                 "Bastia",
  "bolton",                 "bolton",                 "Bolton",
  "bordeaux",               "bordeaux",               "Bordeaux",
  "botafogo rj",            "botafogo rj",         "Botafogo FR RJ",
  "bournemouth",            "bournemouth",            "Bournemouth",
  "braga",               "sp braga",                  "Braga",
  "bragantino",             "bragantino",             "Bragantino",
  "braunschweig",           "braunschweig", "Eintracht Braunschweig",
  "brentford",              "brentford",              "Brentford",
  "brescia",                "brescia",                "Brescia",
  "brest",                  "brest",                  "Brest",
  "brighton",               "brighton", "Brighton and Hove Albion",
  "bristol city",           "bristol city",           "Bristol City",
  "bsad",             "belenenses",             "Belenenses",
  "belgrano",               "belgrano",               "Belgrano",
  "club atletico belgrano",               "belgrano",               "Belgrano",
  "burnley",                "burnley",                "Burnley",
  "cadiz",                  "cadiz",                  "Cadiz",
  "calcio lecco 1912",                  "lecco",                  "Lecco",
  "chambly oise",                  "chambly",                  "Chambly",
  "caen",                   "caen",                   "Caen",
  "clermont foot",                   "clermont",                   "Clermont",
  "cagliari",               "cagliari",               "Cagliari",
  "cambuur",                "cambuur",                "Cambuur",
  "cartagena",              "cartagena",           "FC Cartagena",
  "cardiff city",                "cardiff",           "Cardiff City",
  "casa pia",               "casa pia",               "Casa Pia",
  "ceara",                  "ceara",                  "Ceara",
  "celta vigo",                  "celta",             "Celta Vigo",
  "cc cordoba",        "central cordoba",        "Central Cordoba",
  "cf montreal",            "cf montreal",            "CF Montreal",
  "chapecoense",          "chapecoensesc",          "Chapecoensesc",
  "charlotte",              "charlotte",           "Charlotte FC",
  "charlton ath",               "charlton",               "Charlton",
  "chaves",                 "chaves",                 "Chaves",
  "chelsea",                "chelsea",                "Chelsea",
  "chicago fire",           "chicago fire",           "Chicago Fire",
  "chievo",                 "chievo",                 "Chievo",
  "clermont foot",               "clermont",               "Clermont",
  "colorado rapids",        "colorado rapids",        "Colorado Rapids",
  "colon",         "colon santa fe",      "Colon de Santa Fe",
  "columbus crew",          "columbus crew",          "Columbus Crew",
  "corinthians",            "corinthians",            "Corinthians",
  "coritiba",               "coritiba",               "Coritiba",
  "us concarneau",               "concarneau",               "Concarneau",
  "coventry city",               "coventry",               "Coventry",
  "cremonese",              "cremonese",              "Cremonese",
  "crotone",                "crotone",                "Crotone",
  "cruz azul",              "cruz azul",              "Cruz Azul",
  "cruzeiro",               "cruzeiro",               "Cruzeiro",
  "crystal palace",         "crystal palace",         "Crystal Palace",
  "csa",                    "csa",                    "Csa",
  "cuiaba",                 "cuiaba",                 "Cuiaba",
  "darmstadt 98",              "darmstadt",              "Darmstadt",
  "dc united",              "dc united",            "D.C. United",
  "de graafschap",          "graafschap",          "De Graafschap",
  "defensa y just",     "defensa y justicia",     "Defensa y Justicia",
  "den bosch",              "den bosch",              "Den Bosch",
  "derby county",                  "derby",                  "Derby",
  "dijon",                  "dijon",                  "Dijon",
  "dunkerque",                  "dunkerque",                  "Dunkerque",
  "msv duisburg",                  "duisburg",                  "Duisburg",
  "dortmund",               "dortmund",      "Borussia Dortmund",
  "dusseldorf",     "fortuna dusseldorf",     "Fortuna Dusseldorf",
  "dynamo",         "houston dynamo",         "Houston Dynamo",
  "dynamo fc",         "houston dynamo",         "Houston Dynamo",
  "eibar",                  "eibar",                  "Eibar",
  "eint frankfurt",          "ein frankfurt",    "Eintracht Frankfurt",
  "elche",                  "elche",                  "Elche",
  "elversberg",             "elversberg",             "Elversberg",
  "extremadura",             "extremadura ud",             "Extremadura",
  "cd eldense",                "eldense",                "Eldense",
  "emmen",               "fc emmen",               "Fc Emmen",
  "empoli",                 "empoli",                 "Empoli",
  "espanyol",                "espanol",               "Espanyol",
  "estoril",                "estoril",                "Estoril",
  "estudiantes",         "estudiantes lp","Estudiantes de La Plata",
  "estrela",                "estrela",     "Estrela da Amadora",
  "everton",                "everton",                "Everton",
  "excelsior",              "excelsior",              "Excelsior",
  "excel mouscron",               "mouscron",               "Mouscron",
  "famalicao",              "famalicao",              "Famalicao",
  "farense",                "farense",                "Farense",
  "fc cincinnati",          "fc cincinnati",          "FC Cincinnati",
  "fc dallas",              "fc dallas",                 "Dallas",
  "fc eindhoven",          "psv eindhoven",          "PSV Eindhoven",
  "fc juarez",                 "juarez",              "FC Juarez",
  "feirense",               "feirense",               "Feirense",
  "racing ferrol",                 "ferrol",     "Racing Club Ferrol",
  "feyenoord",              "feyenoord",              "Feyenoord",
  "fiorentina",             "fiorentina",             "Fiorentina",
  "flamengo",            "flamengo rj",               "Flamengo",
  "fluminense",             "fluminense",             "Fluminense",
  "fortaleza",              "fortaleza",              "Fortaleza",
  "fortuna sittard",            "for sittard",        "Fortuna Sittard",
  "freiburg",               "freiburg",               "Freiburg",
  "frosinone",              "frosinone",              "Frosinone",
  "fulham",                 "fulham",                 "Fulham",
  "genoa",                  "genoa",                  "Genoa",
  "getafe",                 "getafe",                 "Getafe",
  "gazelec ajaccio",                 "ajaccio gfco",                 "Gazelec Ajaccio",
  "gil vicente fc",            "gil vicente",            "Gil Vicente",
  "gimnasia elp",            "gimnasia lp",      "Gimnasia La Plata",
  "girona",                 "girona",                 "Girona",
  "go ahead eag",        "go ahead eagles",        "Go Ahead Eagles",
  "godoy cruz",             "godoy cruz",             "Godoy Cruz",
  "goias",                  "goias",                  "Goias",
  "granada",                "granada",             "Granada CF",
  "gremio",                 "gremio",                 "Gremio",
  "grenoble",                 "grenoble",                 "Grenoble",
  "greuther furth",         "greuther furth",         "Greuther Furth",
  "groningen",              "groningen",              "Groningen",
  "guadalajara",     "guadalajara chivas",     "Chivas Guadalajara",
  "guingamp",               "guingamp",               "Guingamp",
  "hamburger sv",                "hamburg",           "Hamburger SV",
  "hannover 96",               "hannover",            "Hannover 96",
  "heidenheim",             "heidenheim",          "FC Heidenheim",
  "heerenveen",             "heerenveen",             "Heerenveen",
  "hansa rostock",          "hansa rostock",          "Hansa Rostock",
  "hellas verona",                 "verona",       "Hellas Verona FC",
  "heracles almelo",               "heracles",        "Heracles Almelo",
  "hertha bsc",                 "hertha",          "Hertha Berlin",
  "hoffenheim",             "hoffenheim",             "Hoffenheim",
  "holstein kiel",          "holstein kiel",          "Holstein Kiel",
  "huddersfield",           "huddersfield",      "Huddersfield Town",
  "huesca",                 "huesca",                 "Huesca",
  "hull city",                   "hull",              "Hull City",
  "ca huracan",                "huracan",                "Huracan",
  "independiente",          "independiente",          "Independiente",
  "inter",                  "inter",      "FC Internazionale",
  "ingolstadt 04",             "ingolstadt",             "Ingolstadt",
  "inter miami",            "inter miami",            "Inter Miami",
  "instituto",              "instituto",   "Instituto AC Cordoba",
  "internacional",          "internacional",          "Internacional",
  "ipswich town",                "ipswich",           "Ipswich Town",
  "juventude",              "juventude",              "Juventude",
  "juventus",               "juventus",               "Juventus",
  "koln",                "fc koln",                "FC Koln",
  "karlsruher",              "karlsruhe",          "Karlsruher SC",
  "kaiserslautern",         "kaiserslautern",         "Kaiserslautern",
  "lanus",                  "lanus",                  "Lanus",
  "la coruna",              "la coruna",              "La Coruna",
  "la galaxy",     "los angeles galaxy",     "Los Angeles Galaxy",
  "las palmas",             "las palmas",             "Las Palmas",
  "lazio",                  "lazio",                  "Lazio",
  "lecce",                  "lecce",                  "Lecce",
  "ud logrones",                  "logrones",                  "Logrones",
  "le havre",               "le havre",               "Le Havre",
  "leeds united",                  "leeds",           "Leeds United",
  "leganes",                "leganes",                "Leganes",
  "leicester city",              "leicester",         "Leicester City",
  "lens",                   "lens",                   "Lens",
  "leon",              "club leon",              "Club Leon",
  "levante",                "levante",             "Levante UD",
  "leverkusen",             "leverkusen",       "Bayer Leverkusen",
  "lille",                  "lille",                  "Lille",
  "liverpool",              "liverpool",              "Liverpool",
  "lobos buap",             "lobos buap",             "Lobos Buap",
  "lorient",                "lorient",                "Lorient",
  "los angeles fc",         "los angeles fc",         "Los Angeles FC",
  "luton town",                  "luton",             "Luton Town",
  "lyon",                   "lyon",                   "Lyon",
  "mainz 05",                  "mainz",               "Mainz 05",
  "malaga",                 "malaga",                 "Malaga",
  "magdeburg",              "magdeburg",           "FC Magdeburg",
  "mallorca",               "mallorca",               "Mallorca",
  "manchester city",               "man city",        "Manchester City",
  "manchester utd",             "man united",      "Manchester United",
  "maritimo",               "maritimo",               "Maritimo",
  "marseille",              "marseille",              "Marseille",
  "mazatlan",            "mazatlan fc",            "Mazatlan FC",
  "metz",                   "metz",                   "Metz",
  "mgladbach",              "mgladbach", "Borussia Monchengladbach",
  "middlesbrough",          "middlesbrough",          "Middlesbrough",
  "milan",                  "milan",               "AC Milan",
  "cd mirandes",               "mirandes",               "Mirandes",
  "millwall",               "millwall",               "Millwall",
  "majadahonda",               "rayo majadahonda",               "Rayo Majadahonda",
  "minnesota utd",       "minnesota united",       "Minnesota United",
  "monaco",                 "monaco",              "AS Monaco",
  "monterrey",              "monterrey",           "CF Monterrey",
  "montpellier",            "montpellier",        "Montpellier HSC",
  "montreal impact",            "cf montreal",            "Cf Montreal",
  "monza",                  "monza",               "AC Monza",
  "moreirense",             "moreirense",             "Moreirense",
  "morelia",               "monarcas",               "Monarcas",
  "mvv maastricht",             "maastricht",             "Maastricht",
  "nac breda",              "nac breda",              "Nac Breda",
  "nacional",               "nacional",               "Nacional",
  "nantes",                 "nantes",                 "Nantes",
  "napoli",                 "napoli",                 "Napoli",
  "nashville",           "nashville sc",           "Nashville SC",
  "nec nijmegen",               "nijmegen",           "NEC Nijmegen",
  "necaxa",                 "necaxa",            "Club Necaxa",
  "new england", "new england revolution", "New England Revolution",
  "newells ob",       "newells old boys",       "Newells Old Boys",
  "newcastle utd",              "newcastle",       "Newcastle United",
  "nice",                   "nice",                   "Nice",
  "nimes",                  "nimes",                  "Nimes",
  "norwich city",                "norwich",           "Norwich City",
  "nottham forest",           "nottm forest",      "Nottingham Forest",
  "nurnberg",               "nurnberg",               "Nurnberg",
  "ny red bulls",     "new york red bulls",     "New York Red Bulls",
  "nycfc",          "new york city",          "New York City",
  "orlando city",           "orlando city",           "Orlando City",
  "osasuna",                "osasuna",                "Osasuna",
  "oh leuven",     "oudheverlee leuven",                 "Leuven",
  "osnabruck",              "osnabruck",              "Osnabruck",
  "oviedo",                 "oviedo",         "Real Oviedo CF",
  "pachuca",                "pachuca",             "CF Pachuca",
  "pacos",         "pacos ferreira",         "Pacos Ferreira",
  "paderborn 07",              "paderborn",              "Paderborn",
  "palmeiras",              "palmeiras",              "Palmeiras",
  "pau fc",              "pau fc",              "Pau fc",
  "paris fc",              "paris fc",              "Paris fc",
  "paris sg",               "paris sg",    "Paris Saint Germain",
  "parma",                  "parma",                  "Parma",
  "pborough utd",              "peterboro",              "Peterboro",
  "philadelphia",     "philadelphia union",     "Philadelphia Union",
  "platense",               "platense",               "Platense",
  "portimonense",           "portimonense",           "Portimonense",
  "plymouth argyle",               "plymouth",        "Plymouth Argyle",
  "portland timbers",       "portland timbers",       "Portland Timbers",
  "porto",                  "porto",               "FC Porto",
  "preston",                "preston",                "Preston",
  "psv eindhoven",          "psv eindhoven",          "Psv Eindhoven",
  "puebla",                 "puebla",              "Puebla FC",
  "qpr",                    "qpr",    "Queens Park Rangers",
  "quevillyrouen",                    "quevilly rouen",    "Quevilly Rouen",
  "queretaro",              "queretaro",           "Queretaro FC",
  "racing club",            "racing club",            "Racing Club",
  "rayo vallecano",              "vallecano",         "Rayo Vallecano",
  "rb leipzig",             "rb leipzig",             "RB Leipzig",
  "reading",                "reading",                "Reading",
  "us reggina",                "reggina",                "Reggina",
  "rodez aveyron",                "rodez",                "Rodez",
  "jahn rburg",             "regensburg",             "Regensburg",
  "real madrid",            "real madrid",            "Real Madrid",
  "real salt lake",         "real salt lake",         "Real Salt Lake",
  "real sociedad",               "sociedad",          "Real Sociedad",
  "real sociedad b",               "sociedad b",          "Real Sociedad B",
  "reims",                  "reims",                  "Reims",
  "reus",                  "reus deportiu",                  "Reus Deportiu",
  "rennes",                 "rennes",                 "Rennes",
  "rio ave",                "rio ave",                "Rio Ave",
  "river plate",            "river plate",            "River Plate",
  "rkc waalwijk",               "waalwijk",           "RKC Waalwijk",
  "roma",                   "roma",                "AS Roma",
  "rosario cent",        "rosario central",        "Rosario Central",
  "rotherham utd",              "rotherham",              "Rotherham",
  "san lorenzo",            "san lorenzo",            "San Lorenzo",
  "saintetienne",             "st etienne",             "St Etienne",
  "salernitana",            "salernitana",            "Salernitana",
  "sarmiento",        "sarmiento junin",     "Sarmiento de Junin",
  "sampdoria",              "sampdoria",              "Sampdoria",
  "san martin",              "san martin t",              "San Martin T",
  "stade laval",              "laval",              "Stade Lavallois",
  "rfc seraing",                "seraing",                "Seraing",
  "san jose",   "san jose earthquakes",   "San Jose Earthquakes",
  "santa clara",            "santa clara",            "Santa Clara",
  "santos",                 "santos",                 "Santos",
  "sinttruiden",             "st truiden",             "St truiden",
  "standard liege",               "standard",         "Standard Liege",
  "racing sant",              "santander",       "Racing Santander",
  "santos laguna",          "santos laguna",     "Club Santos Laguna",
  "sao paulo",              "sao paulo",              "Sao Paulo",
  "sassuolo",               "sassuolo",               "Sassuolo",
  "schalke 04",             "schalke 04",             "Schalke 04",
  "seattle",       "seattle sounders",       "Seattle Sounders",
  "sevilla",                "sevilla",                "Sevilla",
  "saintetienne",                "st etienne",                "St Etienne",
  "sheffield utd",       "sheffield united",       "Sheffield United",
  "sheffield weds",         "sheffield weds",    "Sheffield Wednesday",
  "southampton",            "southampton",            "Southampton",
  "spal",                   "spal",                   "Spal",
  "sporting gijon",               "sp gijon",                  "Gijon",
  "sparta rdam",       "sparta rotterdam",       "Sparta Rotterdam",
  "spezia",                 "spezia",                 "Spezia",
  "sport recife",           "sport recife",           "Sport Recife",
  "sporting cp",              "sp lisbon",            "Sporting CP",
  "sporting kc",   "sporting kansas city",   "Sporting Kansas City",
  "st louis",          "st louis city",      "St. Louis City SC",
  "st pauli",               "st pauli",               "St Pauli",
  "stoke city",                  "stoke",             "Stoke City",
  "strasbourg",             "strasbourg",             "Strasbourg",
  "stuttgart",              "stuttgart",              "Stuttgart",
  "sunderland",             "sunderland",             "Sunderland",
  "swansea city",                "swansea",           "Swansea City",
  "talleres",       "talleres cordoba", "CA Talleres de Cordoba",
  "tenerife",               "tenerife",               "Tenerife",
  "tijuana",           "club tijuana",           "Club Tijuana",
  "tigre",                  "tigre",               "CA Tigre",
  "toluca",                 "toluca",    "Deportivo Toluca FC",
  "tondela",                "tondela",                "Tondela",
  "torino",                 "torino",                 "Torino",
  "toronto fc",             "toronto fc",             "Toronto FC",
  "tottenham",              "tottenham",      "Tottenham Hotspur",
  "toulouse",               "toulouse",            "Toulouse FC",
  "troyes",                 "troyes",                 "Troyes AC",
  "twente",                 "twente",     "FC Twente Enschede",
  "uanl",            "uanl tigres",            "Tigres UANL",
  "udinese",                "udinese",                "Udinese",
  "union sg",            "st gilloise",               "Union Sg",
  "unam",             "unam pumas",             "Pumas UNAM",
  "union berlin",           "union berlin",           "Union Berlin",
  "ca union",     "union de santa fe",         "Union Santa Fe",
  "utrecht",                "utrecht",             "FC Utrecht",
  "valencia",               "valencia",               "Valencia",
  "valenciennes",               "valenciennes",               "Valenciennes FC",
  "valladolid",             "valladolid",     "Real Valladolid CF",
  "vancouver",    "vancouver whitecaps",    "Vancouver Whitecaps",
  "vasco da gama",                  "vasco",          "Vasco Da Gama",
  "venezia",                "venezia",                "Venezia",
  "veracruz",               "veracruz",               "Veracruz",
  "velez sarsfield",        "velez sarsfield",        "Velez Sarsfield",
  "villarreal",             "villarreal",          "Villarreal CF",
  "villarreal b",           "villarreal b",           "Villarreal B",
  "vitesse",                "vitesse",         "Vitesse Arnhem",
  "vitoria",              "guimaraes",      "Vitoria Guimaraes",
  "vitoria setubal",                "setubal",                "Setubal",
  "vizela",                 "vizela",                 "Vizela",
  "vicenza virtus",                 "vicenza",                 "Vicenza",
  "volendam",               "volendam",               "Volendam",
  "vvvvenlo",              "vvv venlo",              "Vvv Venlo",
  "watford",                "watford",                "Watford",
  "werder bremen",          "werder bremen",          "Werder Bremen",
  "west brom",              "west brom",              "West Brom",
  "west ham",               "west ham",        "West Ham United",
  "wehen",                  "wehen",        "Wehen Wiesbaden",
  "wigan athletic",                  "wigan",                  "Wigan",
  "willem ii",              "willem ii",              "Willem Ii",
  "wolfsburg",              "wolfsburg",              "Wolfsburg",
  "wolves",                 "wolves",                 "Wolves",
  "waaslandbev",        "waaslandbeveren",        "Waaslandbeveren",
  "wycombe",                "wycombe",                "Wycombe",
  "wburg kickers",                "wurzburger kickers",                "Wurzburger Kickers",
  "zwolle",                 "zwolle",              "FC Zwolle",
  "zulte waregem",                "waregem",          "Zulte Waregem",
  "zaragoza",               "zaragoza",           "Real Zaragoza"
)

datapasta::dp_set_max_rows(400)
sekasin %>%
  arrange(fbref_name) %>%
  datapasta::dpasta()
