
#' replaces buchdal names with pinnacle
#'
#' @param data account name
#' @param team1 account name
#' @param team2 account name
#' @export
replace_buch_with_pinnacle <- function(data, team1, team2){
  names <- tibble::tribble(
    ~pattern, ~replacement,
    'St. Louis CITY SC', 'St. Louis City SC',
    'FC Arouca', 'Arouca',
    'Instituto', 'Instituto AC Cordoba',
    'Tulsa Roughnecks', 'FC Tulsa',
    'CA Independiente', 'Independiente',
    'Pau', 'Pau FC',
    'Dijon FCO', 'Dijon',
    "Atletico Goianiense", "AC Goianiense GO",
    "SC Farense", "Sporting Farense",
    "Moreirense", "Moreirense FC",
    "Wurzburger Kickers", "FC Wurzburger Kickers",
    "Western United", "Western United FC",
    "Western Sydney FC", "Western Sydney Wanderers",
    "Colon Santa Fe", "Colon de Santa Fe",
    "Estudiantes", "Estudiantes de La Plata",
    "Newell's Old Boys", "Newells Old Boys",
    "Arsenal Sarandi", "Arsenal de Sarandi",
    "Atletico Tucuman", "Atletico Tucuman",
    "Aldosivi", "CA Aldosivi",
    "Patronato", "Patronato Parana",
    "Central Cordoba Santiago del Estero", "Central Cordoba",
    "Talleres de Cordoba", "CA Talleres de Cordoba",
    "Granada", "Granada CF",
    "VfL Osnabruck", "VfL 1899 Osnabruck",
    "SV Wehen Wiesbaden", "Wehen Wiesbaden",
    "Wigan", "Wigan Athletic",
    "Birmingham", "Birmingham City",
    "Newcastle", "Newcastle United",
    "Stade Rennes", "Rennes",
    "Toulouse", "Toulouse FC",
    "Montpellier", "Montpellier HSC",
    "Angers", "Angers SCO",
    "Paris Saint-Germain", "Paris Saint Germain",
    "TSG Hoffenheim", "Hoffenheim",
    "SC Freiburg", "Freiburg",
    "Fortuna Dusseldorf", "Fortuna Dusseldorf",
    "1. FC Nurnberg", "1 FC Nuremberg",
    "Mainz", "Mainz 05",
    "VfL Wolfsburg", "Wolfsburg",
    "VfB Stuttgart", "Stuttgart",
    "FC Augsburg", "Augsburg",
    "1. FC Magdeburg", "FC Magdeburg",
    "1. FC Union Berlin", "Union Berlin",
    "FC Cologne", "FC Koln",
    "MSV Duisburg", "Duisburg",
    "Hamburg SV", "Hamburger SV",
    "Verona", "Hellas Verona FC",
    'Las Vegas Lights FC', 'Las Vegas Lights',
    "Chievo Hellas Verona FC", "AC Chievo Verona",
    "Internazionale", "FC Internazionale",
    "Atalanta", "Atalanta BC",
    "F.B.C Unione Venezia", "Venezia",
    "Queretaro", "Queretaro FC",
    "CF America", "Club America",
    "Monterrey", "CF Monterrey",
    "Pumas Unam", "Pumas UNAM",
    "Lobos de la BUAP", "CF Lobos de la BUAP",
    "Puebla", "Puebla FC",
    "Leon", "Club Leon",
    "Guadalajara", "Chivas Guadalajara",
    "Tijuana", "Club Tijuana",
    "C.D. Nacional", "CD Nacional Madeira",
    "Desportivo Aves", "Aves",
    "Girona FC", "Girona",
    "Alaves", "Alaves",
    "Levante", "Levante UD",
    "Sevilla FC", "Sevilla",
    "Real Valladolid", "Real Valladolid CF",
    "Villarreal", "Villarreal CF",
    "Athletic Bilbao", "Athletic Club Bilbao",
    "SD Huesca", "Huesca",
    "Orlando City SC", "Orlando City",
    "New York City FC", "New York City",
    "DC United", "D.C. United",
    "Seattle Sounders FC", "Seattle Sounders",
    "Minnesota United FC", "Minnesota United",
    "FC Dallas", "Dallas",
    "Blackburn", "Blackburn Rovers",
    "Wolverhampton", "Wolves",
    "US Pescara", "Delfino Pescara 1936",
    "Pachuca", "CF Pachuca",
    "Club America", "CF America",
    "Atlanta United FC", "Atlanta United",
    "Botafogo", "Botafogo FR RJ",
    "Grêmio", "Gremio FB Porto Alegrense RS",
    "Ceara", "Ceara SC CE",
    "Chapecoense AF", "Chapecoense SC",
    "Avai", "Avai FC SC",
    "CSA", "Centro Sportivo Alagoano",
    "Chongqing Lifan", "Chongqing SWM",
    "Guizhou Renhe", "Beijing Renhe",
    "Hebei China Fortune FC", "Hebei CFFC",
    "Tianjin Quanujian", "Tianjin Tianhai",
    "Guangzhou RF", "Guangzhou R&F",
    "Guangzhou Evergrande", "Guangzhou Evergrande Taobao",
    "Shanghai SIPG", "Shanghai Sipg",
    "Tianjin Teda", "Tianjin Teda FC",
    "Shanghai Greenland", "Shanghai Shenhua",
    "FC Juarez", "FC Juarez",
    "Atletico San Luis", "Atletico San Luis",
    "Morelia", "CA Monarcas Morelia",
    "Santos SP Laguna", "Club Santos Laguna",
    "Toluca", "Deportivo Toluca FC",
    "Newcastle United Jets", "Newcastle Jets",
    "Inter Miami CF", "Inter Miami",
    "Mazatlan FC", "Mazatlan FC",
    "Elche", "Elche CF",
    "Monza", "AC Monza",
    "FC Twente", "FC Twente Enschede",
    "Vitesse", "Vitesse Arnhem",
    "Heracles", "Heracles Almelo",
    "Sparta", "Sparta Rotterdam",
    "PSV", "PSV Eindhoven",
    "AZ", "Az Alkmaar",
    "Az Alkmaar", "AZ Alkmaar",
    "RKC", "RKC Waalwijk",
    "SV Zulte Waregem", "SV Zulte-Waregem",
    "Valenciennes", "Valenciennes FC",
    "Chambly Thelle FC", "FC Chambly Oise",
    "Sporting Gijon", "Gijon",
    "AD Alcorcon", "Alcorcon",
    "Lausanne Sports", "Lausanne",
    "FC Salzburg", "Red Bull Salzburg",
    "Antwerp", "Royal Antwerp",
    "Ludogorets", "Ludogorets 1947",
    "Lugo", "CD Lugo",
    "SD Ponferradina", "Ponferradina",
    "CD Sabadell", "CE Sabadell FC",
    "Logrones", "UD Logrones",
    "SK Sturm Graz", "Sturm Graz",
    "KV Oostende", "Oostende",
    "Niort", "Chamois Niortais FC",
    "US Quevilly", "Quevilly",
    "Dunkerque", "USL Dunkerque",
    "WSG Swarovski Wattens", "WSG Wattens",
    "FC Trenkwalder Admira", "FC Admira Wacker Modling",
    "Sporting de Charleroi", "Charleroi",
    "KAA Gent", "Gent",
    "Mouscron-Peruwelz", "Mouscron Peruwelz",
    "OH Leuven", "Oud-Heverlee Leuven",
    "St. Truidense", "Sint Truiden",
    "Bolton", "Bolton Wanderers",
    "Real Oviedo", "Real Oviedo CF",
    "FC Khimki", "Khimki",
    "SK Brann", "Brann",
    "Rosenborg", "Rosenborg BK",
    "Aalesund", "Aalesunds",
    "Vicenza", "LR Vicenza Virtus",
    "Scunthorpe", "Scunthorpe United",
    "Reggiana", "AC Reggiana",
    "Cremonese", "US Cremonese",
    "Salernitana", "Sportiva Salernitana",
    "Doncaster Rovers", "Doncaster",
    "Milton Keynes Dons", "MK Dons",
    "Shrewsbury Town", "Shrewsbury",
    'Brentford', 'Brentford FC',
    'Norwich City', 'Norwich City FC',
    'Antalyaspor', 'Antalyaspor AS',
    'Goztepe', 'Goztepe SK',
    'Ankaragucu', 'MKE Ankaragucu',
    'Jahn Regensburg', 'SSV Jahn Regensburg',
    'Emmen', 'FC Emmen',
    'Feyenoord', 'Feyenoord Rotterdam',
    'Tondela', 'CD Tondela',
    'Belgrano Cordoba', 'Belgrano',
    'Belenenses', 'Belenenses SAD',
    'Heerenveen', 'SC Heerenveen',
    'Portimonense', 'Portimonense SC',
    'Guimaraes', 'Vitoria Guimarares',
    'Ajax', 'Ajax Amsterdam',
    'Oklahoma City Energy FC', 'OKC Energy FC',
    'Rio Grande Valley FC Toros', 'Rio Grande Valley FC',
    'Birmingham City Legion FC', 'Birmingham Legion FC',
    'Troyes', 'Troyes AC',
    'Loudoun United FC', 'Loudoun United Fc',
    'Santos FC SP Laguna', 'Club Santos Laguna',
    'Birmingham Legion FC', 'Birmingham Legion Fc',
    'Oakland Roots', 'Oakland Roots Sc',
    'El Paso Locomotive FC', 'El Paso Locomotive Fc',
    'Norwich City FC', 'Norwich City',
    'Brentford FC', 'Brentford',
    'Norwich City FC', 'Norwich City',
    'Watford FC', 'Watford',
    'Sportiva Salernitana', 'Salernitana',
    'VfL Bochum', 'Bochum',
    'AFC Bournemouth', 'Bournemouth',
    'NEC', 'NEC Nijmegen',
    'AS Nancy Lorraine', 'AS Nancy-Lorraine',
    'Auxerre', 'AJ Auxerre',
    'Krylia Sovetov', 'Kryliya Sovetov',
    'FK Nizhny Novgorod', 'Olimpiyets Nizhny Novgorod',
    'Rotherham United', 'Rotherham',
    'Wycombe Wanderers', 'Wycombe',
    'Clermont Foot', 'Clermont',
    'Altay', 'Altay Izmir',
    'Burgos', 'CD Burgos',
    'Red Bull SC Bragantino SP', 'Red Bull Bragantino SP',
    'LA Galaxy II', 'Los Angeles Galaxy II',
    'Preston North End', 'Preston',
    'West Bromwich Albion', 'West Brom',
    'Coventry City', 'Coventry',
    'Estoril Praia', 'Estoril',
    'FC St. Pau FCli', 'FC St. Pauli',
    'Crotone', 'FC Crotone',
    'Alessandria', 'US Alessandria Calcio 1912',
    'Sao Pau FClo', 'Sao Paulo FC SP',
    'Sao Paulo FC SP', 'Sao Paulo',
    'FC Sheriff Tiraspol', 'Sheriff Tiraspol',
    'Ludogorets 1947', 'Ludogorets 1945',
    'Feyenoord Rotterdam', 'Feyenoord',
    'FC St. Pauli', 'St Pauli',
    'FC Ingolstadt 04', 'Ingolstadt',
    'SV Sandhausen', 'Sandhausen',
    '1. FC Heidenheim 1846', 'FC Heidenheim',
    'SC Paderborn', 'Paderborn',
    'Cambuur Leeuwarden', 'Cambuur Leeuwaarden',
    'Patronato Parana', 'CA Patronato Parana',
    "Sarmiento", "Sarmiento de Junin",
    'SC Heerenveen', 'Heerenveen',
    'FC Groningen', 'Groningen',
    'Ajax Amsterdam', 'Ajax',
    'PEC Zwolle', 'FC Zwolle',
    '1 FC Nuremberg', 'Nurnberg',
    'SSV Jahn Regensburg', 'Jahn Regensburg',
    'Memphis 901 FC', 'Memphis 901 Fc',
    'SpVgg Greuther Furth', 'Greuther Furth',
    'Montreal Impact', 'CF Montreal',
    'Necaxa', 'Club Necaxa',
    'Tigre', 'CA Tigre',
    'AJ Auxerre', 'Auxerre',
    'US Cremonese', 'Cremonese',
    '1. FC Kaiserslautern', 'Kaiserslautern',
    'FC Emmen', 'Emmen',
    'FC Volendam', 'Volendam',
    'Laval', 'Stade Lavallois',
    'CA Tigres UANL', 'Tigres UANL',
    'Villarreal CF B', 'Villarreal B',
    'SV Darmstadt 98', 'Darmstadt'
  )
  # Making the named replacement vector
  replacements <- c(names$replacement)
  names(replacements) <- c(names$pattern)

  data %>%
    dplyr::group_by(league) %>%
    dplyr::mutate(across(c({{team1}},{{team2}}), ~stringr::str_replace_all(., pattern = replacements))) %>%
    dplyr::ungroup()
}
