#' team look up table
#'
#' @return A tribble
#' @export
team_dictionary <- function(){

tibble::tribble(
                ~fbref_name,               ~buch_name,                  ~pin_name,
             "ado den haag",               "den haag",                 "Den Haag",
                  "ajaccio",                "ajaccio",               "AC Ajaccio",
                     "ajax",                   "ajax",                     "Ajax",
                   "alaves",                 "alaves",                   "Alaves",
                 "albacete",               "albacete",                 "Albacete",
                 "alcorcon",               "alcorcon",                 "Alcorcon",
              "almere city",            "almere city",              "Almere City",
                  "almeria",                "almeria",                  "Almeria",
                  "america",           "club america",               "CF America",
               "america mg",             "america mg",          "America Mineiro",
                   "amiens",                 "amiens",                   "Amiens",
                   "angers",                 "angers",               "Angers SCO",
                   "annecy",                 "annecy",                   "Annecy",
           "argentinos jun",         "argentinos jrs",       "Argentinos Juniors",
                  "arminia",              "bielefeld",                "Bielefeld",
                   "arouca",                 "arouca",                   "Arouca",
                  "arsenal",                "arsenal",                  "Arsenal",
          "arsenal sarandi",        "arsenal sarandi",       "Arsenal de Sarandi",
              "aston villa",            "aston villa",              "Aston Villa",
                 "atalanta",               "atalanta",              "Atalanta BC",
           "ath paranaense",            "athleticopr",     "Athletico Paranaense",
            "athletic club",             "ath bilbao",     "Athletic Club Bilbao",
           "atl goianiense",            "atletico go",              "Atletico Go",
              "atlanta utd",            "atlanta utd",           "Atlanta United",
                    "atlas",                  "atlas",                    "Atlas",
                 "atletico",           "atl san luis",        "Atletico San Luis",
          "atletico madrid",             "ath madrid",          "Atletico Madrid",
         "atletico mineiro",             "atleticomg",         "Atletico Mineiro",
                 "augsburg",               "augsburg",                 "Augsburg",
                   "austin",              "austin fc",                "Austin FC",
                  "auxerre",                "auxerre",                  "Auxerre",
                     "avai",                   "avai",                     "Avai",
                     "aves",                   "aves",                     "Aves",
               "az alkmaar",             "az alkmaar",               "AZ Alkmaar",
                    "bahia",                  "bahia",                    "Bahia",
                 "banfield",               "banfield",                 "Banfield",
                "barcelona",              "barcelona",                "Barcelona",
                 "barnsley",               "barnsley",                 "Barnsley",
         "barracas central",       "barracas central",         "Barracas Central",
                   "bastia",                 "bastia",                   "Bastia",
            "bayern munich",          "bayern munich",            "Bayern Munich",
                "beerschot",           "beerschot va",                "Beerschot",
                 "belgrano",               "belgrano",                 "Belgrano",
                "benevento",              "benevento",                "Benevento",
                  "benfica",                "benfica",                  "Benfica",
                    "betis",                  "betis",               "Real Betis",
          "birmingham city",             "birmingham",          "Birmingham City",
                "blackburn",              "blackburn",         "Blackburn Rovers",
                "blackpool",              "blackpool",                "Blackpool",
                 "boavista",               "boavista",                 "Boavista",
             "boca juniors",           "boca juniors",             "Boca Juniors",
                   "bochum",                 "bochum",                   "Bochum",
                  "bologna",                "bologna",                  "Bologna",
                   "bolton",                 "bolton",                   "Bolton",
                 "bordeaux",               "bordeaux",                 "Bordeaux",
              "botafogo rj",            "botafogo rj",           "Botafogo FR RJ",
              "bournemouth",            "bournemouth",              "Bournemouth",
                    "braga",               "sp braga",                    "Braga",
               "bragantino",             "bragantino",               "Bragantino",
             "braunschweig",           "braunschweig",   "Eintracht Braunschweig",
                "brentford",              "brentford",                "Brentford",
                  "brescia",                "brescia",                  "Brescia",
                    "brest",                  "brest",                    "Brest",
                 "brighton",               "brighton", "Brighton and Hove Albion",
             "bristol city",           "bristol city",             "Bristol City",
                     "bsad",             "belenenses",               "Belenenses",
                   "burgos",                 "burgos",                "CD Burgos",
                  "burnley",                "burnley",                  "Burnley",
               "ca huracan",                "huracan",                  "Huracan",
                 "ca union",      "union de santa fe",           "Union Santa Fe",
                    "cadiz",                  "cadiz",                    "Cadiz",
                     "caen",                   "caen",                     "Caen",
                 "cagliari",               "cagliari",                 "Cagliari",
        "calcio lecco 1912",                  "lecco",                    "Lecco",
                  "cambuur",                "cambuur",                  "Cambuur",
             "cardiff city",                "cardiff",             "Cardiff City",
                "cartagena",              "cartagena",             "FC Cartagena",
                 "casa pia",               "casa pia",                 "Casa Pia",
               "cc cordoba",        "central cordoba",          "Central Cordoba",
               "cd eldense",                "eldense",                  "Eldense",
              "cd mirandes",               "mirandes",                 "Mirandes",
                    "ceara",                  "ceara",                    "Ceara",
               "celta vigo",                  "celta",               "Celta Vigo",
              "cf montreal",            "cf montreal",              "CF Montreal",
             "chambly oise",                "chambly",                  "Chambly",
              "chapecoense",          "chapecoensesc",            "Chapecoensesc",
                "charlotte",              "charlotte",             "Charlotte FC",
             "charlton ath",               "charlton",                 "Charlton",
                   "chaves",                 "chaves",                   "Chaves",
                  "chelsea",                "chelsea",                  "Chelsea",
             "chicago fire",           "chicago fire",             "Chicago Fire",
                   "chievo",                 "chievo",                   "Chievo",
            "clermont foot",               "clermont",                 "Clermont",
            "clermont foot",               "clermont",                 "Clermont",
   "club atletico belgrano",               "belgrano",                 "Belgrano",
                    "colon",         "colon santa fe",        "Colon de Santa Fe",
          "colorado rapids",        "colorado rapids",          "Colorado Rapids",
            "columbus crew",          "columbus crew",            "Columbus Crew",
              "corinthians",            "corinthians",              "Corinthians",
                 "coritiba",               "coritiba",                 "Coritiba",
            "coventry city",               "coventry",                 "Coventry",
                "cremonese",              "cremonese",                "Cremonese",
                  "crotone",                "crotone",                  "Crotone",
                "cruz azul",              "cruz azul",                "Cruz Azul",
                 "cruzeiro",               "cruzeiro",                 "Cruzeiro",
           "crystal palace",         "crystal palace",           "Crystal Palace",
                      "csa",                    "csa",                      "Csa",
                   "cuiaba",                 "cuiaba",                   "Cuiaba",
             "darmstadt 98",              "darmstadt",                "Darmstadt",
                "dc united",              "dc united",              "D.C. United",
            "de graafschap",             "graafschap",            "De Graafschap",
           "defensa y just",     "defensa y justicia",       "Defensa y Justicia",
                "den bosch",              "den bosch",                "Den Bosch",
             "derby county",                  "derby",                    "Derby",
                    "dijon",                  "dijon",                    "Dijon",
                 "dortmund",               "dortmund",        "Borussia Dortmund",
                "dunkerque",              "dunkerque",                "Dunkerque",
               "dusseldorf",     "fortuna dusseldorf",       "Fortuna Dusseldorf",
                   "dynamo",         "houston dynamo",           "Houston Dynamo",
                "dynamo fc",         "houston dynamo",           "Houston Dynamo",
                    "eibar",                  "eibar",                    "Eibar",
           "eint frankfurt",          "ein frankfurt",      "Eintracht Frankfurt",
                    "elche",                  "elche",                    "Elche",
               "elversberg",             "elversberg",               "Elversberg",
                    "emmen",               "fc emmen",                 "Fc Emmen",
                   "empoli",                 "empoli",                   "Empoli",
                 "espanyol",                "espanol",                 "Espanyol",
                  "estoril",                "estoril",                  "Estoril",
                  "estrela",                "estrela",       "Estrela da Amadora",
              "estudiantes",         "estudiantes lp",  "Estudiantes de La Plata",
                  "everton",                "everton",                  "Everton",
           "excel mouscron",               "mouscron",                 "Mouscron",
                "excelsior",              "excelsior",                "Excelsior",
              "extremadura",         "extremadura ud",              "Extremadura",
                "famalicao",              "famalicao",                "Famalicao",
                  "farense",                "farense",                  "Farense",
               "fc andorra",                "andorra",               "FC Andorra",
            "fc cincinnati",          "fc cincinnati",            "FC Cincinnati",
                "fc dallas",              "fc dallas",                   "Dallas",
             "fc eindhoven",          "psv eindhoven",            "PSV Eindhoven",
                "fc juarez",                 "juarez",                "FC Juarez",
                 "feirense",               "feirense",                 "Feirense",
                "feyenoord",              "feyenoord",                "Feyenoord",
               "fiorentina",             "fiorentina",               "Fiorentina",
                 "flamengo",            "flamengo rj",                 "Flamengo",
               "fluminense",             "fluminense",               "Fluminense",
                "fortaleza",              "fortaleza",                "Fortaleza",
          "fortuna sittard",            "for sittard",          "Fortuna Sittard",
                 "freiburg",               "freiburg",                 "Freiburg",
                "frosinone",              "frosinone",                "Frosinone",
                   "fulham",                 "fulham",                   "Fulham",
          "gazelec ajaccio",           "ajaccio gfco",          "Gazelec Ajaccio",
                    "genoa",                  "genoa",                    "Genoa",
                   "getafe",                 "getafe",                   "Getafe",
           "gil vicente fc",            "gil vicente",              "Gil Vicente",
             "gimnasia elp",            "gimnasia lp",        "Gimnasia La Plata",
                   "girona",                 "girona",                   "Girona",
             "go ahead eag",        "go ahead eagles",          "Go Ahead Eagles",
               "godoy cruz",             "godoy cruz",               "Godoy Cruz",
                    "goias",                  "goias",                    "Goias",
                  "granada",                "granada",               "Granada CF",
                   "gremio",                 "gremio",                   "Gremio",
                 "grenoble",               "grenoble",                 "Grenoble",
           "greuther furth",         "greuther furth",           "Greuther Furth",
                "groningen",              "groningen",                "Groningen",
              "guadalajara",     "guadalajara chivas",       "Chivas Guadalajara",
                 "guingamp",               "guingamp",                 "Guingamp",
             "hamburger sv",                "hamburg",             "Hamburger SV",
              "hannover 96",               "hannover",              "Hannover 96",
            "hansa rostock",          "hansa rostock",            "Hansa Rostock",
               "heerenveen",             "heerenveen",               "Heerenveen",
               "heidenheim",             "heidenheim",            "FC Heidenheim",
            "hellas verona",                 "verona",         "Hellas Verona FC",
          "heracles almelo",               "heracles",          "Heracles Almelo",
               "hertha bsc",                 "hertha",            "Hertha Berlin",
               "hoffenheim",             "hoffenheim",               "Hoffenheim",
            "holstein kiel",          "holstein kiel",            "Holstein Kiel",
             "huddersfield",           "huddersfield",        "Huddersfield Town",
                   "huesca",                 "huesca",                   "Huesca",
                "hull city",                   "hull",                "Hull City",
            "independiente",          "independiente",            "Independiente",
            "ingolstadt 04",             "ingolstadt",               "Ingolstadt",
                "instituto",              "instituto",     "Instituto AC Cordoba",
                    "inter",                  "inter",        "FC Internazionale",
              "inter miami",            "inter miami",              "Inter Miami",
            "internacional",          "internacional",            "Internacional",
             "ipswich town",                "ipswich",             "Ipswich Town",
               "jahn rburg",             "regensburg",               "Regensburg",
                "juventude",              "juventude",                "Juventude",
                 "juventus",               "juventus",                 "Juventus",
           "kaiserslautern",         "kaiserslautern",           "Kaiserslautern",
               "karlsruher",              "karlsruhe",            "Karlsruher SC",
                     "koln",                "fc koln",                  "FC Koln",
                "la coruna",              "la coruna",                "La Coruna",
                "la galaxy",     "los angeles galaxy",       "Los Angeles Galaxy",
                    "lanus",                  "lanus",                    "Lanus",
               "las palmas",             "las palmas",               "Las Palmas",
                    "lazio",                  "lazio",                    "Lazio",
                 "le havre",               "le havre",                 "Le Havre",
                    "lecce",                  "lecce",                    "Lecce",
             "leeds united",                  "leeds",             "Leeds United",
                  "leganes",                "leganes",                  "Leganes",
           "leicester city",              "leicester",           "Leicester City",
                     "lens",                   "lens",                     "Lens",
                     "leon",              "club leon",                "Club Leon",
                  "levante",                "levante",               "Levante UD",
               "leverkusen",             "leverkusen",         "Bayer Leverkusen",
                    "lille",                  "lille",                    "Lille",
                "liverpool",              "liverpool",                "Liverpool",
               "lobos buap",             "lobos buap",               "Lobos Buap",
                  "lorient",                "lorient",                  "Lorient",
           "los angeles fc",         "los angeles fc",           "Los Angeles FC",
               "luton town",                  "luton",               "Luton Town",
                     "lyon",                   "lyon",                     "Lyon",
                "magdeburg",              "magdeburg",             "FC Magdeburg",
                 "mainz 05",                  "mainz",                 "Mainz 05",
              "majadahonda",       "rayo majadahonda",         "Rayo Majadahonda",
                   "malaga",                 "malaga",                   "Malaga",
                 "mallorca",               "mallorca",                 "Mallorca",
          "manchester city",               "man city",          "Manchester City",
           "manchester utd",             "man united",        "Manchester United",
                 "maritimo",               "maritimo",                 "Maritimo",
                "marseille",              "marseille",                "Marseille",
                 "mazatlan",            "mazatlan fc",              "Mazatlan FC",
                     "metz",                   "metz",                     "Metz",
                "mgladbach",              "mgladbach", "Borussia Monchengladbach",
            "middlesbrough",          "middlesbrough",            "Middlesbrough",
                    "milan",                  "milan",                 "AC Milan",
                 "millwall",               "millwall",                 "Millwall",
            "minnesota utd",       "minnesota united",         "Minnesota United",
                   "monaco",                 "monaco",                "AS Monaco",
                "monterrey",              "monterrey",             "CF Monterrey",
              "montpellier",            "montpellier",          "Montpellier HSC",
          "montreal impact",            "cf montreal",              "Cf Montreal",
                    "monza",                  "monza",                 "AC Monza",
               "moreirense",             "moreirense",               "Moreirense",
                  "morelia",               "monarcas",                 "Monarcas",
             "msv duisburg",               "duisburg",                 "Duisburg",
           "mvv maastricht",             "maastricht",               "Maastricht",
                "nac breda",              "nac breda",                "Nac Breda",
                 "nacional",               "nacional",                 "Nacional",
                   "nantes",                 "nantes",                   "Nantes",
                   "napoli",                 "napoli",                   "Napoli",
                "nashville",           "nashville sc",             "Nashville SC",
             "nec nijmegen",               "nijmegen",             "NEC Nijmegen",
                   "necaxa",                 "necaxa",              "Club Necaxa",
              "new england", "new england revolution",   "New England Revolution",
            "newcastle utd",              "newcastle",         "Newcastle United",
               "newells ob",       "newells old boys",         "Newells Old Boys",
                     "nice",                   "nice",                     "Nice",
                    "nimes",                  "nimes",                    "Nimes",
             "norwich city",                "norwich",             "Norwich City",
           "nottham forest",           "nottm forest",        "Nottingham Forest",
                 "nurnberg",               "nurnberg",                 "Nurnberg",
             "ny red bulls",     "new york red bulls",       "New York Red Bulls",
                    "nycfc",          "new york city",            "New York City",
                "oh leuven",     "oudheverlee leuven",                   "Leuven",
             "orlando city",           "orlando city",             "Orlando City",
                  "osasuna",                "osasuna",                  "Osasuna",
                "osnabruck",              "osnabruck",                "Osnabruck",
                   "oviedo",                 "oviedo",           "Real Oviedo CF",
                  "pachuca",                "pachuca",               "CF Pachuca",
                    "pacos",         "pacos ferreira",           "Pacos Ferreira",
             "paderborn 07",              "paderborn",                "Paderborn",
                "palmeiras",              "palmeiras",                "Palmeiras",
                 "paris fc",               "paris fc",                 "Paris FC",
                 "paris sg",               "paris sg",      "Paris Saint Germain",
                    "parma",                  "parma",                    "Parma",
                   "pau fc",                 "pau fc",                   "Pau FC",
             "pborough utd",              "peterboro",                "Peterboro",
             "philadelphia",     "philadelphia union",       "Philadelphia Union",
                 "platense",               "platense",                 "Platense",
          "plymouth argyle",               "plymouth",          "Plymouth Argyle",
             "portimonense",           "portimonense",             "Portimonense",
         "portland timbers",       "portland timbers",         "Portland Timbers",
                    "porto",                  "porto",                 "FC Porto",
                  "preston",                "preston",                  "Preston",
            "psv eindhoven",          "psv eindhoven",            "Psv Eindhoven",
                   "puebla",                 "puebla",                "Puebla FC",
                      "qpr",                    "qpr",      "Queens Park Rangers",
                "queretaro",              "queretaro",             "Queretaro FC",
            "quevillyrouen",         "quevilly rouen",                 "Quevilly",
              "racing club",            "racing club",              "Racing Club",
            "racing ferrol",                 "ferrol",       "Racing Club Ferrol",
              "racing sant",              "santander",         "Racing Santander",
           "rayo vallecano",              "vallecano",           "Rayo Vallecano",
               "rb leipzig",             "rb leipzig",               "RB Leipzig",
                  "reading",                "reading",                  "Reading",
              "real madrid",            "real madrid",              "Real Madrid",
           "real salt lake",         "real salt lake",           "Real Salt Lake",
            "real sociedad",               "sociedad",            "Real Sociedad",
          "real sociedad b",             "sociedad b",          "Real Sociedad B",
                    "reims",                  "reims",                    "Reims",
                   "rennes",                 "rennes",                   "Rennes",
                     "reus",          "reus deportiu",            "Reus Deportiu",
              "rfc seraing",                "seraing",                  "Seraing",
                  "rio ave",                "rio ave",                  "Rio Ave",
              "river plate",            "river plate",              "River Plate",
             "rkc waalwijk",               "waalwijk",             "RKC Waalwijk",
            "rodez aveyron",                  "rodez",                    "Rodez",
                     "roma",                   "roma",                  "AS Roma",
             "rosario cent",        "rosario central",          "Rosario Central",
            "rotherham utd",              "rotherham",                "Rotherham",
             "saintetienne",             "st etienne",               "St Etienne",
             "saintetienne",             "st etienne",               "St Etienne",
              "salernitana",            "salernitana",              "Salernitana",
                "sampdoria",              "sampdoria",                "Sampdoria",
                 "san jose",   "san jose earthquakes",     "San Jose Earthquakes",
              "san lorenzo",            "san lorenzo",              "San Lorenzo",
               "san martin",           "san martin t",             "San Martin T",
              "santa clara",            "santa clara",              "Santa Clara",
                   "santos",                 "santos",                   "Santos",
            "santos laguna",          "santos laguna",       "Club Santos Laguna",
                "sao paulo",              "sao paulo",                "Sao Paulo",
                "sarmiento",        "sarmiento junin",       "Sarmiento de Junin",
                 "sassuolo",               "sassuolo",                 "Sassuolo",
               "schalke 04",             "schalke 04",               "Schalke 04",
            "sd amorebieta",             "amorebieta",               "Amorebieta",
                  "seattle",       "seattle sounders",         "Seattle Sounders",
                  "sevilla",                "sevilla",                  "Sevilla",
            "sheffield utd",       "sheffield united",         "Sheffield United",
           "sheffield weds",         "sheffield weds",      "Sheffield Wednesday",
              "sinttruiden",             "st truiden",               "St truiden",
              "southampton",            "southampton",              "Southampton",
                     "spal",                   "spal",                     "Spal",
              "sparta rdam",       "sparta rotterdam",         "Sparta Rotterdam",
                   "spezia",                 "spezia",                   "Spezia",
             "sport recife",           "sport recife",             "Sport Recife",
              "sporting cp",              "sp lisbon",              "Sporting CP",
           "sporting gijon",               "sp gijon",                    "Gijon",
              "sporting kc",   "sporting kansas city",     "Sporting Kansas City",
                 "st louis",          "st louis city",        "St. Louis City SC",
                 "st pauli",               "st pauli",                 "St Pauli",
              "stade laval",                  "laval",          "Stade Lavallois",
           "standard liege",               "standard",           "Standard Liege",
               "stoke city",                  "stoke",               "Stoke City",
               "strasbourg",             "strasbourg",               "Strasbourg",
                "stuttgart",              "stuttgart",                "Stuttgart",
               "sunderland",             "sunderland",               "Sunderland",
             "swansea city",                "swansea",             "Swansea City",
                 "talleres",       "talleres cordoba",   "CA Talleres de Cordoba",
                 "tenerife",               "tenerife",                 "Tenerife",
                    "tigre",                  "tigre",                 "CA Tigre",
                  "tijuana",           "club tijuana",             "Club Tijuana",
                   "toluca",                 "toluca",      "Deportivo Toluca FC",
                  "tondela",                "tondela",                  "Tondela",
                   "torino",                 "torino",                   "Torino",
               "toronto fc",             "toronto fc",               "Toronto FC",
                "tottenham",              "tottenham",        "Tottenham Hotspur",
                 "toulouse",               "toulouse",              "Toulouse FC",
                   "troyes",                 "troyes",                "Troyes AC",
                  "tucuman",            "atl tucuman",         "Atletico Tucuman",
                   "twente",                 "twente",       "FC Twente Enschede",
                     "uanl",            "uanl tigres",              "Tigres UANL",
              "ud logrones",               "logrones",                 "Logrones",
                  "udinese",                "udinese",                  "Udinese",
                     "unam",             "unam pumas",               "Pumas UNAM",
             "union berlin",           "union berlin",             "Union Berlin",
                 "union sg",            "st gilloise",                 "Union Sg",
            "us concarneau",             "concarneau",               "Concarneau",
               "us reggina",                "reggina",                  "Reggina",
                  "utrecht",                "utrecht",               "FC Utrecht",
                 "valencia",               "valencia",                 "Valencia",
             "valenciennes",           "valenciennes",          "Valenciennes FC",
               "valladolid",             "valladolid",       "Real Valladolid CF",
                "vancouver",    "vancouver whitecaps",      "Vancouver Whitecaps",
            "vasco da gama",                  "vasco",            "Vasco Da Gama",
          "velez sarsfield",        "velez sarsfield",          "Velez Sarsfield",
                  "venezia",                "venezia",                  "Venezia",
                 "veracruz",               "veracruz",                 "Veracruz",
           "vicenza virtus",                "vicenza",                  "Vicenza",
               "villarreal",             "villarreal",            "Villarreal CF",
             "villarreal b",           "villarreal b",             "Villarreal B",
                  "vitesse",                "vitesse",           "Vitesse Arnhem",
                  "vitoria",              "guimaraes",        "Vitoria Guimaraes",
          "vitoria setubal",                "setubal",                  "Setubal",
                   "vizela",                 "vizela",                   "Vizela",
                 "volendam",               "volendam",                 "Volendam",
                 "vvvvenlo",              "vvv venlo",                "Vvv Venlo",
              "waaslandbev",        "waaslandbeveren",          "Waaslandbeveren",
                  "watford",                "watford",                  "Watford",
            "wburg kickers",     "wurzburger kickers",       "Wurzburger Kickers",
                    "wehen",                  "wehen",          "Wehen Wiesbaden",
            "werder bremen",          "werder bremen",            "Werder Bremen",
                "west brom",              "west brom",                "West Brom",
                 "west ham",               "west ham",          "West Ham United",
           "wigan athletic",                  "wigan",                    "Wigan",
                "willem ii",              "willem ii",                "Willem Ii",
                "wolfsburg",              "wolfsburg",                "Wolfsburg",
                   "wolves",                 "wolves",                   "Wolves",
                  "wycombe",                "wycombe",                  "Wycombe",
                 "zaragoza",               "zaragoza",            "Real Zaragoza",
            "zulte waregem",                "waregem",            "Zulte Waregem",
                   "zwolle",                 "zwolle",                "FC Zwolle"
   )
}

