#' team look up table
#'
#' @return A tribble
#' @export
team_dictionary <- function(){
tibble::tribble(
         ~fbref_name,               ~buch_name,                ~pin_name,
      "ado den haag",               "den haag",               "Den Haag",
           "ajaccio",                "ajaccio",                "Ajaccio",
              "ajax",                   "ajax",                   "Ajax",
            "alaves",                 "alaves",                 "Alaves",
       "almere city",            "almere city",            "Almere City",
           "almeria",                "almeria",                "Almeria",
           "america",           "club america",             "CF America",
        "america mg",             "america mg",        "America Mineiro",
            "amiens",                 "amiens",                 "Amiens",
        "amorebieta",             "amorebieta",             "Amorebieta",
          "albacete",               "albacete",               "Albacete",
            "angers",                 "angers",                 "Angers",
           "andorra",                "andorra",             "FC Andorra",
           "arminia",              "bielefeld",              "Bielefeld",
            "arouca",                 "arouca",                 "Arouca",
           "arsenal",                "arsenal",                "Arsenal",
   "arsenal sarandi",        "arsenal sarandi",     "Arsenal de Sarandi",
       "aston villa",            "aston villa",            "Aston Villa",
          "atalanta",               "atalanta",            "Atalanta BC",
     "athletic club",             "ath bilbao",   "Athletic Club Bilbao",
          "atletico",           "atl san luis",      "Atletico San Luis",
    "atl goianiense",            "atletico go",            "Atletico Go",
    "ath paranaense",            "athleticopr",   "Athletico Paranaense",
       "atl tucuman",            "atl tucuman",       "Atletico Tucuman",
       "atlanta utd",            "atlanta utd",         "Atlanta United",
             "atlas",                  "atlas",                  "Atlas",
   "atletico madrid",             "ath madrid",        "Atletico Madrid",
  "atletico mineiro",             "atleticomg",       "Atletico Mineiro",
          "augsburg",               "augsburg",               "Augsburg",
            "austin",              "austin fc",              "Austin FC",
           "auxerre",                "auxerre",                "Auxerre",
    "argentinos jrs",         "argentinos jrs",     "Argentinos Juniors",
              "avai",                   "avai",                   "Avai",
              "aves",                   "aves",                   "Aves",
        "az alkmaar",             "az alkmaar",             "AZ Alkmaar",
             "bahia",                  "bahia",                  "Bahia",
         "barcelona",              "barcelona",              "Barcelona",
          "barnsley",               "barnsley",               "Barnsley",
  "barracas central",       "barracas central",       "Barracas Central",
          "banfield",               "banfield",               "Banfield",
     "bayern munich",          "bayern munich",          "Bayern Munich",
         "benevento",              "benevento",              "Benevento",
           "benfica",                "benfica",                "Benfica",
             "betis",                  "betis",             "Real Betis",
   "birmingham city",             "birmingham",        "Birmingham City",
         "blackburn",              "blackburn",       "Blackburn Rovers",
         "blackpool",              "blackpool",              "Blackpool",
          "boavista",               "boavista",               "Boavista",
            "bochum",                 "bochum",                 "Bochum",
      "boca juniors",           "boca juniors",           "Boca Juniors",
           "bologna",                "bologna",                "Bologna",
            "bolton",                 "bolton",                 "Bolton",
          "bordeaux",               "bordeaux",               "Bordeaux",
       "botafogo rj",            "botafogo rj",         "Botafogo FR RJ",
       "bournemouth",            "bournemouth",            "Bournemouth",
             "braga",               "sp braga",               "Sp Braga",
        "bragantino",             "bragantino",             "Bragantino",
      "braunschweig",           "braunschweig", "Eintracht Braunschweig",
         "brentford",              "brentford",              "Brentford",
           "brescia",                "brescia",                "Brescia",
             "brest",                  "brest",                  "Brest",
          "brighton",               "brighton", "Brighton and Hove Albion",
      "bristol city",           "bristol city",           "Bristol City",
              "bsad",             "belenenses",             "Belenenses",
          "belgrano",               "belgrano",               "Belgrano",
           "burnley",                "burnley",                "Burnley",
             "cadiz",                  "cadiz",                  "Cadiz",
              "caen",                   "caen",                   "Caen",
          "cagliari",               "cagliari",               "Cagliari",
           "cambuur",                "cambuur",                "Cambuur",
         "cartagena",              "cartagena",           "FC Cartagena",
      "cardiff city",                "cardiff",           "Cardiff City",
          "casa pia",               "casa pia",               "Casa Pia",
             "ceara",                  "ceara",                  "Ceara",
        "celta vigo",                  "celta",             "Celta Vigo",
   "central cordoba",        "central cordoba",        "Central Cordoba",
       "cf montreal",            "cf montreal",            "CF Montreal",
       "chapecoense",          "chapecoensesc",          "Chapecoensesc",
         "charlotte",              "charlotte",           "Charlotte FC",
      "charlton ath",               "charlton",               "Charlton",
            "chaves",                 "chaves",                 "Chaves",
           "chelsea",                "chelsea",                "Chelsea",
      "chicago fire",           "chicago fire",           "Chicago Fire",
            "chievo",                 "chievo",                 "Chievo",
     "clermont foot",               "clermont",               "Clermont",
   "colorado rapids",        "colorado rapids",        "Colorado Rapids",
    "colon santa fe",         "colon santa fe",      "Colon de Santa Fe",
     "columbus crew",          "columbus crew",          "Columbus Crew",
       "corinthians",            "corinthians",            "Corinthians",
          "coritiba",               "coritiba",               "Coritiba",
     "coventry city",               "coventry",               "Coventry",
         "cremonese",              "cremonese",              "Cremonese",
           "crotone",                "crotone",                "Crotone",
         "cruz azul",              "cruz azul",              "Cruz Azul",
          "cruzeiro",               "cruzeiro",               "Cruzeiro",
    "crystal palace",         "crystal palace",         "Crystal Palace",
               "csa",                    "csa",                    "Csa",
            "cuiaba",                 "cuiaba",                 "Cuiaba",
      "darmstadt 98",              "darmstadt",              "Darmstadt",
         "dc united",              "dc united",            "D.C. United",
     "de graafschap",          "de graafschap",          "De Graafschap",
"defensa y justicia",     "defensa y justicia",     "Defensa y Justicia",
         "den bosch",              "den bosch",              "Den Bosch",
      "derby county",                  "derby",                  "Derby",
             "dijon",                  "dijon",                  "Dijon",
          "dortmund",               "dortmund",               "Dortmund",
        "dusseldorf",     "fortuna dusseldorf",     "Fortuna Dusseldorf",
            "dynamo",         "houston dynamo",         "Houston Dynamo",
         "dynamo fc",         "houston dynamo",         "Houston Dynamo",
             "eibar",                  "eibar",                  "Eibar",
    "eint frankfurt",          "ein frankfurt",    "Eintracht Frankfurt",
             "elche",                  "elche",                  "Elche",
           "eldense",                "eldense",                "Eldense",
             "emmen",               "fc emmen",               "Fc Emmen",
            "empoli",                 "empoli",                 "Empoli",
          "espanyol",                "espanol",               "Espanyol",
           "estoril",                "estoril",                "Estoril",
    "estudiantes lp",         "estudiantes lp","Estudiantes de La Plata",
           "estrela",                "estrela",                "Estrela",
           "everton",                "everton",                "Everton",
         "excelsior",              "excelsior",              "Excelsior",
         "famalicao",              "famalicao",              "Famalicao",
           "farense",                "farense",                "Farense",
     "fc cincinnati",          "fc cincinnati",          "FC Cincinnati",
         "fc dallas",              "fc dallas",                 "Dallas",
      "fc eindhoven",          "psv eindhoven",          "PSV Eindhoven",
         "fc juarez",                 "juarez",              "FC Juarez",
          "feirense",               "feirense",               "Feirense",
            "ferrol",                 "ferrol",     "Racing Club Ferrol",
         "feyenoord",              "feyenoord",              "Feyenoord",
        "fiorentina",             "fiorentina",             "Fiorentina",
          "flamengo",            "flamengo rj",               "Flamengo",
        "fluminense",             "fluminense",             "Fluminense",
         "fortaleza",              "fortaleza",              "Fortaleza",
   "fortuna sittard",            "for sittard",        "Fortuna Sittard",
          "freiburg",               "freiburg",               "Freiburg",
         "frosinone",              "frosinone",              "Frosinone",
            "fulham",                 "fulham",                 "Fulham",
             "genoa",                  "genoa",                  "Genoa",
            "getafe",                 "getafe",                 "Getafe",
    "gil vicente fc",            "gil vicente",            "Gil Vicente",
       "gimnasia lp",            "gimnasia lp",      "Gimnasia La Plata",
            "girona",                 "girona",                 "Girona",
      "go ahead eag",        "go ahead eagles",        "Go Ahead Eagles",
        "godoy cruz",             "godoy cruz",             "Godoy Cruz",
             "goias",                  "goias",                  "Goias",
           "granada",                "granada",             "Granada CF",
            "gremio",                 "gremio",                 "Gremio",
    "greuther furth",         "greuther furth",         "Greuther Furth",
         "groningen",              "groningen",              "Groningen",
       "guadalajara",     "guadalajara chivas",     "Chivas Guadalajara",
          "guingamp",               "guingamp",               "Guingamp",
      "hamburger sv",                "hamburg",                "Hamburg",
       "hannover 96",               "hannover",               "Hannover",
        "heerenveen",             "heerenveen",             "Heerenveen",
        "heidenheim",             "heidenheim",             "Heidenheim",
     "hellas verona",                 "verona",       "Hellas Verona FC",
   "heracles almelo",               "heracles",        "Heracles Almelo",
        "hertha bsc",                 "hertha",                 "Hertha",
        "hoffenheim",             "hoffenheim",             "Hoffenheim",
     "holstein kiel",          "holstein kiel",          "Holstein Kiel",
      "huddersfield",           "huddersfield",      "Huddersfield Town",
            "huesca",                 "huesca",                 "Huesca",
         "hull city",                   "hull",              "Hull City",
           "huracan",                "huracan",                "Huracan",
     "independiente",          "independiente",          "Independiente",
             "inter",                  "inter",      "FC Internazionale",
       "inter miami",            "inter miami",            "Inter Miami",
         "instituto",              "instituto",   "Instituto AC Cordoba",
     "internacional",          "internacional",          "Internacional",
      "ipswich town",                "ipswich",           "Ipswich Town",
         "juventude",              "juventude",              "Juventude",
          "juventus",               "juventus",               "Juventus",
              "koln",                "fc koln",                "Fc Koln",
         "karlsruhe",              "karlsruhe",          "Karlsruher SC",
             "lanus",                  "lanus",                  "Lanus",
         "la coruna",              "la coruna",              "La Coruna",
         "la galaxy",     "los angeles galaxy",     "Los Angeles Galaxy",
        "las palmas",             "las palmas",             "Las Palmas",
             "lazio",                  "lazio",                  "Lazio",
             "lecce",                  "lecce",                  "Lecce",
          "le havre",               "le havre",               "Le Havre",
      "leeds united",                  "leeds",           "Leeds United",
           "leganes",                "leganes",                "Leganes",
    "leicester city",              "leicester",         "Leicester City",
              "lens",                   "lens",                   "Lens",
              "leon",              "club leon",              "Club Leon",
           "levante",                "levante",             "Levante UD",
        "leverkusen",             "leverkusen",             "Leverkusen",
             "lille",                  "lille",                  "Lille",
         "liverpool",              "liverpool",              "Liverpool",
        "lobos buap",             "lobos buap",             "Lobos Buap",
           "lorient",                "lorient",                "Lorient",
    "los angeles fc",         "los angeles fc",         "Los Angeles FC",
        "luton town",                  "luton",             "Luton Town",
              "lyon",                   "lyon",                   "Lyon",
          "mainz 05",                  "mainz",                  "Mainz",
            "malaga",                 "malaga",                 "Malaga",
         "magdeburg",              "magdeburg",           "FC Magdeburg",
          "mallorca",               "mallorca",               "Mallorca",
   "manchester city",               "man city",        "Manchester City",
    "manchester utd",             "man united",      "Manchester United",
          "maritimo",               "maritimo",               "Maritimo",
         "marseille",              "marseille",              "Marseille",
          "mazatlan",            "mazatlan fc",            "Mazatlan FC",
              "metz",                   "metz",                   "Metz",
         "mgladbach",              "mgladbach",              "Mgladbach",
     "middlesbrough",          "middlesbrough",          "Middlesbrough",
             "milan",                  "milan",               "AC Milan",
          "mirandes",               "mirandes",               "Mirandes",
          "millwall",               "millwall",               "Millwall",
     "minnesota utd",       "minnesota united",       "Minnesota United",
            "monaco",                 "monaco",              "AS Monaco",
         "monterrey",              "monterrey",           "CF Monterrey",
       "montpellier",            "montpellier",        "Montpellier HSC",
   "montreal impact",            "cf montreal",            "Cf Montreal",
             "monza",                  "monza",               "AC Monza",
        "moreirense",             "moreirense",             "Moreirense",
           "morelia",               "monarcas",               "Monarcas",
    "mvv maastricht",             "maastricht",             "Maastricht",
         "nac breda",              "nac breda",              "Nac Breda",
          "nacional",               "nacional",               "Nacional",
            "nantes",                 "nantes",                 "Nantes",
            "napoli",                 "napoli",                 "Napoli",
         "nashville",           "nashville sc",           "Nashville SC",
      "nec nijmegen",               "nijmegen",               "Nijmegen",
            "necaxa",                 "necaxa",            "Club Necaxa",
       "new england", "new england revolution", "New England Revolution",
  "newells old boys",       "newells old boys",       "Newells Old Boys",
     "newcastle utd",              "newcastle",       "Newcastle United",
              "nice",                   "nice",                   "Nice",
             "nimes",                  "nimes",                  "Nimes",
      "norwich city",                "norwich",           "Norwich City",
    "nottham forest",           "nottm forest",      "Nottingham Forest",
          "nurnberg",               "nurnberg",               "Nurnberg",
      "ny red bulls",     "new york red bulls",     "New York Red Bulls",
             "nycfc",          "new york city",          "New York City",
      "orlando city",           "orlando city",           "Orlando City",
           "osasuna",                "osasuna",                "Osasuna",
            "oviedo",                 "oviedo",         "Real Oviedo CF",
           "pachuca",                "pachuca",             "CF Pachuca",
             "pacos",         "pacos ferreira",         "Pacos Ferreira",
      "paderborn 07",              "paderborn",              "Paderborn",
         "palmeiras",              "palmeiras",              "Palmeiras",
          "paris sg",               "paris sg",    "Paris Saint Germain",
             "parma",                  "parma",                  "Parma",
      "pborough utd",              "peterboro",              "Peterboro",
      "philadelphia",     "philadelphia union",     "Philadelphia Union",
          "platense",               "platense",               "Platense",
      "portimonense",           "portimonense",           "Portimonense",
   "plymouth argyle",               "plymouth",        "Plymouth Argyle",
  "portland timbers",       "portland timbers",       "Portland Timbers",
             "porto",                  "porto",               "FC Porto",
           "preston",                "preston",                "Preston",
     "psv eindhoven",          "psv eindhoven",          "Psv Eindhoven",
            "puebla",                 "puebla",              "Puebla FC",
               "qpr",                    "qpr",    "Queens Park Rangers",
         "queretaro",              "queretaro",           "Queretaro FC",
       "racing club",            "racing club",            "Racing Club",
    "rayo vallecano",              "vallecano",         "Rayo Vallecano",
        "rb leipzig",             "rb leipzig",             "Rb Leipzig",
           "reading",                "reading",                "Reading",
       "real madrid",            "real madrid",            "Real Madrid",
    "real salt lake",         "real salt lake",         "Real Salt Lake",
     "real sociedad",               "sociedad",          "Real Sociedad",
             "reims",                  "reims",                  "Reims",
            "rennes",                 "rennes",                 "Rennes",
           "rio ave",                "rio ave",                "Rio Ave",
       "river plate",            "river plate",            "River Plate",
      "rkc waalwijk",               "waalwijk",               "Waalwijk",
              "roma",                   "roma",                "AS Roma",
   "rosario central",        "rosario central",        "Rosario Central",
     "rotherham utd",              "rotherham",              "Rotherham",
       "san lorenzo",            "san lorenzo",            "San Lorenzo",
      "saintetienne",             "st etienne",             "St Etienne",
       "salernitana",            "salernitana",            "Salernitana",
   "sarmiento junin",        "sarmiento junin",     "Sarmiento de Junin",
         "sampdoria",              "sampdoria",              "Sampdoria",
          "san jose",   "san jose earthquakes",   "San Jose Earthquakes",
       "santa clara",            "santa clara",            "Santa Clara",
            "santos",                 "santos",                 "Santos",
         "santander",              "santander",       "Racing Santander",
     "santos laguna",          "santos laguna",     "Club Santos Laguna",
         "sao paulo",              "sao paulo",              "Sao Paulo",
          "sassuolo",               "sassuolo",               "Sassuolo",
        "schalke 04",             "schalke 04",             "Schalke 04",
           "seattle",       "seattle sounders",       "Seattle Sounders",
           "sevilla",                "sevilla",                "Sevilla",
     "sheffield utd",       "sheffield united",       "Sheffield United",
    "sheffield weds",         "sheffield weds",    "Sheffield Wednesday",
       "southampton",            "southampton",            "Southampton",
              "spal",                   "spal",                   "Spal",
    "sporting gijon",               "sp gijon",                  "Gijon",
       "sparta rdam",       "sparta rotterdam",       "Sparta Rotterdam",
            "spezia",                 "spezia",                 "Spezia",
      "sport recife",           "sport recife",           "Sport Recife",
       "sporting cp",              "sp lisbon",            "Sporting CP",
       "sporting kc",   "sporting kansas city",   "Sporting Kansas City",
          "st louis",          "st louis city",      "St. Louis City SC",
          "st pauli",               "st pauli",               "St Pauli",
        "stoke city",                  "stoke",             "Stoke City",
        "strasbourg",             "strasbourg",             "Strasbourg",
         "stuttgart",              "stuttgart",              "Stuttgart",
        "sunderland",             "sunderland",             "Sunderland",
      "swansea city",                "swansea",           "Swansea City",
  "talleres cordoba",       "talleres cordoba", "CA Talleres de Cordoba",
           "tijuana",           "club tijuana",           "Club Tijuana",
             "tigre",                  "tigre",               "CA Tigre",
            "toluca",                 "toluca",    "Deportivo Toluca FC",
           "tondela",                "tondela",                "Tondela",
            "torino",                 "torino",                 "Torino",
        "toronto fc",             "toronto fc",             "Toronto FC",
         "tottenham",              "tottenham",      "Tottenham Hotspur",
          "toulouse",               "toulouse",            "Toulouse FC",
            "troyes",                 "troyes",                 "Troyes",
            "twente",                 "twente",     "FC Twente Enschede",
              "uanl",            "uanl tigres",            "Tigres UANL",
           "udinese",                "udinese",                "Udinese",
              "unam",             "unam pumas",             "Pumas UNAM",
      "union berlin",           "union berlin",           "Union Berlin",
  "union de santa fe",     "union de santa fe",         "Union Santa Fe",
           "utrecht",                "utrecht",             "FC Utrecht",
          "valencia",               "valencia",               "Valencia",
        "valladolid",             "valladolid",             "Valladolid",
         "vancouver",    "vancouver whitecaps",    "Vancouver Whitecaps",
     "vasco da gama",                  "vasco",          "Vasco Da Gama",
           "venezia",                "venezia",                "Venezia",
          "veracruz",               "veracruz",               "Veracruz",
   "velez sarsfield",        "velez sarsfield",        "Velez Sarsfield",
        "villarreal",             "villarreal",          "Villarreal CF",
      "villarreal b",           "villarreal b",           "Villarreal B",
           "vitesse",                "vitesse",         "Vitesse Arnhem",
           "vitoria",              "guimaraes",      "Vitoria Guimaraes",
   "vitoria setubal",                "setubal",                "Setubal",
            "vizela",                 "vizela",                 "Vizela",
          "volendam",               "volendam",               "Volendam",
          "vvvvenlo",              "vvv venlo",              "Vvv Venlo",
           "watford",                "watford",                "Watford",
     "werder bremen",          "werder bremen",          "Werder Bremen",
         "west brom",              "west brom",              "West Brom",
          "west ham",               "west ham",        "West Ham United",
             "wehen",                  "wehen",        "Wehen Wiesbaden",
    "wigan athletic",                  "wigan",                  "Wigan",
         "willem ii",              "willem ii",              "Willem Ii",
         "wolfsburg",              "wolfsburg",              "Wolfsburg",
            "wolves",                 "wolves",                 "Wolves",
           "wycombe",                "wycombe",                "Wycombe",
            "zwolle",                 "zwolle",               "FC Zwolle"
  )
}
